import urllib.request, json

URL = "https://mnmotdluigzeehdjbhbu.supabase.co/rest/v1/driving_questions"
KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ubW90ZGx1aWd6ZWVoZGpiaGJ1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MDMzNzA4NCwiZXhwIjoyMDg1OTEzMDg0fQ.Fn-8x3vlgyU8OP6D5Cz1jiA7qSjqnXV5Wx-hR3nl5cc"

QUESTIONS = [
  # ── VÄGMÄRKEN ──
  {"category":"Vägmärken","difficulty":"easy","question":"Vad innebär ett runt blått märke med en vit pil rakt upp?","option_a":"Motortrafik förbjuden","option_b":"Påbjuden körriktning rakt fram","option_c":"Hastighetsbegränsning upphör","option_d":"Avkörning förbjuden","correct":"B","explanation":"Runda blå märken med vita pilar är påbudsmärken. Pil rakt upp = du måste fortsätta rakt fram."},
  {"category":"Vägmärken","difficulty":"normal","question":"Vad innebär ett vitt märke med röd kant och ett rött snedstreck?","option_a":"Förbud mot infart","option_b":"Stopplikt","option_c":"Väjningsplikt","option_d":"Parkering förbjuden","correct":"A","explanation":"Märket 'Förbud mot infart' (B1) har vit bakgrund med röd kant och rött snedstreck. Ingen trafik får köra in på den vägen."},
  {"category":"Vägmärken","difficulty":"easy","question":"Vad innebär ett gult varningsmärke med en svart bil som glider i sida?","option_a":"Varning för is och snö","option_b":"Varning för slirigt väglag","option_c":"Varning för backig väg","option_d":"Varning för vägkorsning","correct":"B","explanation":"Det gula varningsmärket med ett fordon i sladd varnar för särskilt halt och slirigt väglag. Minska hastigheten."},
  {"category":"Vägmärken","difficulty":"normal","question":"Vad innebär ett grönmärke med vit motorvägssymbol?","option_a":"Motortrafikled börjar","option_b":"Motorväg börjar","option_c":"Huvudled börjar","option_d":"Genomfartsled","correct":"B","explanation":"Gröna märken med vit motorvägsymbol markerar att motorvägen börjar med tillhörande regler."},
  {"category":"Vägmärken","difficulty":"normal","question":"Vad innebär ett rött triangelmärke med en svart järnväg och bommar?","option_a":"Järnvägskorsning med bommar","option_b":"Spårväg korsar","option_c":"Järnvägskorsning utan bommar","option_d":"Järnvägsstation","correct":"A","explanation":"Triangelmärket med järnväg och bommar varnar för en bevakad järnvägskorsning. Sakta ner och var beredd att stanna."},
  {"category":"Vägmärken","difficulty":"easy","question":"Vad innebär det vita märket med ett rött P och ett diagonalt streck?","option_a":"Parkering tillåten","option_b":"Parkering förbjuden","option_c":"Stannande förbjudet","option_d":"Lastning förbjuden","correct":"B","explanation":"Märket 'Parkering förbjuden' är vitt med rött P och ett snedstreck. Du får inte parkera på platsen."},
  {"category":"Vägmärken","difficulty":"normal","question":"Vad innebär ett blått märke med en vit buss?","option_a":"Busstation","option_b":"Busshållplats","option_c":"Bussfil","option_d":"Bussar har förkörsrätt","correct":"B","explanation":"Det blå märket med vit bussymbol markerar en busshållplats. Parkering är förbjuden i zonen."},
  {"category":"Vägmärken","difficulty":"easy","question":"Vad innebär ett gult varningsmärke med en triangel och ett utropstecken?","option_a":"Varning för vägarbete","option_b":"Varning – okänd fara","option_c":"Varning för djur","option_d":"Varning för halt väglag","correct":"B","explanation":"Det gula triangelmärket med utropstecken är ett generellt varningmärke för 'annan fara'. En tilläggsskylt specificerar ofta faran."},
  {"category":"Vägmärken","difficulty":"hard","question":"Vad innebär ett vitt märke med texten 'ZONE 30' i rött?","option_a":"Hastighetsbegränsning 30 km/h i hela zonen","option_b":"Tillfällig 30-begränsning","option_c":"Genomfartshastighet 30 km/h","option_d":"Rekommenderad hastighet 30 km/h","correct":"A","explanation":"Zone 30-märket markerar ett område där 30 km/h gäller på alla gator tills du ser ett 'Zone 30 slut'-märke."},
  {"category":"Vägmärken","difficulty":"normal","question":"Vad innebär ett gult märke med en pil rakt fram och en böjd pil till sidan?","option_a":"Korsning med förkörsrätt","option_b":"Vägkorsning utan förkörsrätt","option_c":"Farlig kurva","option_d":"Vägvisare för omväg","correct":"A","explanation":"Det gula märket med pilar visar att du är på huvudleden med förkörsrätt. Sidotrafik måste ge dig företräde."},
  {"category":"Vägmärken","difficulty":"hard","question":"Vad innebär ett märke med en röd triangel och pilar uppåt och nedåt?","option_a":"Varning för möte med mötande trafik","option_b":"Smal väg – möte kan kräva att en stanna","option_c":"Varning för att vägen slutar","option_d":"Varning för tvåfältstrafik","correct":"B","explanation":"Märket 'Smal väg' varnar för att vägen är så smal att mötande fordon kan behöva stanna för att passera."},
  {"category":"Vägmärken","difficulty":"easy","question":"Vad innebär ett runt rött märke med en vit horisontell linje?","option_a":"Förbud mot infart","option_b":"Förbud mot all trafik","option_c":"Stannande förbjudet","option_d":"Väjningsplikt","correct":"A","explanation":"Det runda märket med vit horisontell linje (B1) är 'Förbud mot infart'. Ingen trafik i den riktningen."},
  {"category":"Vägmärken","difficulty":"normal","question":"Vad innebär ett märke med en röd triangel och en svart gående person?","option_a":"Varning för skola","option_b":"Varning för gångtrafikanter","option_c":"Övergångställe ahead","option_d":"Gångfartsområde","correct":"B","explanation":"Det gula triangelmärket med en gående person varnar förare om att gångtrafikanter kan korsa eller röra sig längs vägen."},
  {"category":"Vägmärken","difficulty":"hard","question":"Vilket märke visar att du lämnar en motorväg?","option_a":"Blått märke med vit pil nedåt","option_b":"Grönt märke med vit motorvägssymbol och streck","option_c":"Gult märke med svart pil","option_d":"Vitt märke med röd kant","correct":"B","explanation":"Märket 'Motorväg slut' är grönt med motorvägssymbol och ett genomstrykningstecken. Det innebär att motorvägsreglerna upphör."},
  {"category":"Vägmärken","difficulty":"easy","question":"Vad innebär ett runt blått märke med vita pilar som visar vänster och höger?","option_a":"Vägen delar sig – välj sida","option_b":"Påbjuden körriktning – du måste svänga","option_c":"Rekommendation att svänga","option_d":"Omkörningsförbud upphör","correct":"B","explanation":"Runda blå märken med vita pilar är påbudsmärken. Pilar som visar vänster och höger innebär att du måste svänga åt något av de angivna hållen."},

  # ── TRAFIKREGLER ──
  {"category":"Trafikregler","difficulty":"easy","question":"Hur långt från ett övergångställe får du parkera?","option_a":"5 meter","option_b":"10 meter","option_c":"15 meter","option_d":"20 meter","correct":"B","explanation":"Du får inte parkera inom 10 meter från ett övergångställe. Det ger förare sikt att se gångtrafikanter i tid."},
  {"category":"Trafikregler","difficulty":"normal","question":"Vad innebär dubbla heldragna gula mittlinjer?","option_a":"Du får köra om om det är säkert","option_b":"Varken du eller mötande fordon får korsa linjerna","option_c":"Endast mötande fordon får korsa","option_d":"Gäller bara vid dåligt väder","correct":"B","explanation":"Dubbla heldragna gula mittlinjer innebär absolut körförbud för båda riktningarna. De finns vid platser med extremt dålig sikt."},
  {"category":"Trafikregler","difficulty":"easy","question":"Är det tillåtet att använda handhållen mobiltelefon under körning?","option_a":"Ja, om det inte stör körningen","option_b":"Ja, vid kortare samtal","option_c":"Nej, det är förbjudet","option_d":"Ja, om hastigheten är under 30 km/h","correct":"C","explanation":"Det är förbjudet att hålla i och använda mobiltelefon under körning. Böter utdelas. Handsfree är tillåtet."},
  {"category":"Trafikregler","difficulty":"normal","question":"Vad innebär det att en annan förare blinkar med halvljuset bakifrån på dig?","option_a":"De vill köra om dig – du håller för låg hastighet","option_b":"De varnar för fara framför","option_c":"De vill att du ska stanna","option_d":"De har problem med sina ljus","correct":"A","explanation":"Att blinka med halvljuset bakifrån (ljustuta) signalerar att du kör för sakta. Håll dig till höger och låt fordonet passera."},
  {"category":"Trafikregler","difficulty":"easy","question":"Vad gäller för barn under 135 cm långa som åker bil?","option_a":"De ska sitta bak","option_b":"De ska ha en godkänd bilbarnstol eller boosterkudde","option_c":"De får åka utan bälte om de är under 3 år","option_d":"De ska bara bära säkerhetsbälte","correct":"B","explanation":"Barn under 135 cm måste använda ett godkänt barnskyddssystem anpassat för deras vikt och längd. Föraren ansvarar."},
  {"category":"Trafikregler","difficulty":"normal","question":"Vad innebär ett gult X ovanför ett körfält på motorväg?","option_a":"Kör försiktigt, möjlig fara","option_b":"Körfältet är stängt – lämna det omedelbart","option_c":"Sänk hastigheten till 30 km/h","option_d":"Rekommenderat körfält för tung trafik","correct":"B","explanation":"Ett gult X ovanför ett körfält innebär att körfältet är stängt. Du måste byta körfält omedelbart."},
  {"category":"Trafikregler","difficulty":"normal","question":"Vad gäller parkering framför en garageuppfart?","option_a":"Tillåtet om du parkerar högst 30 min","option_b":"Alltid förbjudet","option_c":"Tillåtet om garaget inte är i bruk","option_d":"Tillåtet om du lämnar kontaktuppgifter","correct":"B","explanation":"Parkering framför garageuppfart är alltid förbjudet. Det hindrar ägare från att komma ut eller in."},
  {"category":"Trafikregler","difficulty":"hard","question":"Vilka fordon får normalt köra i en bussfil?","option_a":"Taxi och buss","option_b":"Enbart bussar i linjetrafik","option_c":"Cyklar, taxi och bussar","option_d":"Alla fordon i nödsituation","correct":"A","explanation":"I en bussfil får normalt bussar i linjetrafik och taxi köra. Lokal tilläggsskylt kan medge fler fordon."},
  {"category":"Trafikregler","difficulty":"easy","question":"Vilka ljus ska du använda vid mörker på väl upplyst tätortsväg?","option_a":"Helljus","option_b":"Halvljus","option_c":"Parkeringsljus","option_d":"Inga ljus behövs","correct":"B","explanation":"Även på väl upplysta gator ska du använda halvljus i mörker. Parkeringsljus räcker inte, och helljus bländar mötande."},
  {"category":"Trafikregler","difficulty":"normal","question":"Vad ska du göra när du passerar en stillastående spårvagn som tar upp passagerare?","option_a":"Kör om på höger sida om det finns plats","option_b":"Stanna och vänta tills alla passagerare är säkert på trottoaren","option_c":"Sänk hastigheten och passera försiktigt","option_d":"Stanna bakom spårvagnen alltid","correct":"B","explanation":"Stanna och vänta tills spårvagnens dörrar stängs. Att köra om en stillastående spårvagn vars passagerare kliver av/på är förbjudet."},
  {"category":"Trafikregler","difficulty":"hard","question":"Hur många meter framför ett backkrön med skymd sikt får du parkera?","option_a":"25 meter","option_b":"50 meter","option_c":"75 meter","option_d":"100 meter","correct":"B","explanation":"Du får inte parkera inom 50 meter framför ett backkrön eller kurva med begränsad sikt. Parkerade fordon kan vara osynliga och farliga."},
  {"category":"Trafikregler","difficulty":"normal","question":"Vad gäller varningsblinkers på motorväg?","option_a":"Används vid nödbroms och vid köbildning","option_b":"Får inte användas på motorväg","option_c":"Ska alltid vara på vid körning","option_d":"Används bara vid regn","correct":"A","explanation":"Varningsblinkers ska användas vid nödbroms, om du tvingas stanna på motorväg, eller för att varna bakifrån vid plötslig köbildning."},
  {"category":"Trafikregler","difficulty":"easy","question":"Vad innebär 'gående har företräde' vid ett övergångställe?","option_a":"Du ska stanna om gående finns inom 50 meter","option_b":"Fordon ska sakta ner och ge gångtrafikanter möjlighet att passera","option_c":"Gående kan gå utan att titta","option_d":"Gäller bara när trafikljus visar rött","correct":"B","explanation":"Vid övergångställe ska fordon lämna företräde till gångtrafikanter som är på eller ska gå ut på övergångsstället."},
  {"category":"Trafikregler","difficulty":"hard","question":"Vad gäller om du märker att du kört fel riktning på motorväg?","option_a":"Vänd om på närmaste bra plats","option_b":"Backa till närmaste avfart","option_c":"Kör till närmaste avfart och vänd där","option_d":"Stanna och ring polisen","correct":"C","explanation":"På motorväg är det förbjudet att stanna, backa eller vända. Kör till närmaste avfart och vänd om där."},
  {"category":"Trafikregler","difficulty":"normal","question":"Vilket minsta avstånd bör du hålla till fordonet framför under normala förhållanden?","option_a":"Halvt sekundens körväg","option_b":"En sekunds körväg","option_c":"Två sekunders körväg","option_d":"Tre sekunders körväg","correct":"C","explanation":"Tumregeln är minst 2 sekunders avstånd under normala förhållanden. Välj ett fast objekt och räkna sekunder. Vid dåligt väder öka till 4-6 sekunder."},

  # ── KORSNINGAR ──
  {"category":"Korsningar","difficulty":"easy","question":"Du svänger höger i en korsning. Vilka ska du ge företräde åt?","option_a":"Ingen – svängande fordon har företräde","option_b":"Gångtrafikanter och cyklister på överfarten","option_c":"Mötande trafik","option_d":"Fordon som kör rakt fram","correct":"B","explanation":"När du svänger måste du alltid ge företräde till gångtrafikanter och cyklister på överfarten, oavsett svängriktning."},
  {"category":"Korsningar","difficulty":"normal","question":"Trafikljuset visar rött. Du vill svänga höger. Är det tillåtet?","option_a":"Ja, om det är säkert","option_b":"Ja, om det finns en separat grön pil","option_c":"Nej, alltid förbjudet vid rött","option_d":"Ja, efter att ha stannat","correct":"C","explanation":"I Sverige är det förbjudet att svänga höger vid rött om det inte finns en separat grön pil som uttryckligen tillåter det."},
  {"category":"Korsningar","difficulty":"hard","question":"Mötande bil ska svänga vänster i korsningen. Du kör rakt fram. Vem ger företräde?","option_a":"Den som svänger vänster","option_b":"Du som kör rakt fram","option_c":"Den som kört in i korsningen sist","option_d":"Den med tyngst fordon","correct":"B","explanation":"Den som svänger vänster måste alltid ge företräde åt mötande trafik som kör rakt fram eller svänger höger."},
  {"category":"Korsningar","difficulty":"normal","question":"Du ska köra in i en rondell. Vem har företräde?","option_a":"Du som kör in","option_b":"Fordon som redan kör i rondellen","option_c":"Tung trafik","option_d":"Den som är snabbast","correct":"B","explanation":"I en rondell har fordon som redan kör i rondellen alltid företräde. Du som kör in måste väja."},
  {"category":"Korsningar","difficulty":"normal","question":"En ambulans med blåljus och siren är bakom dig i en korsning. Vad gör du?","option_a":"Accelerera och lämna korsningen snabbt","option_b":"Stanna direkt i korsningen","option_c":"Genomför manövern säkert och ge sedan plats","option_d":"Ignorera det","correct":"C","explanation":"Slutför din manöver säkert, kör ur korsningen och dra åt sidan. Stanna aldrig i mitten av en korsning."},
  {"category":"Korsningar","difficulty":"hard","question":"Det finns inga märken i korsningen och du möter en spårvagn. Vem har företräde?","option_a":"Du har alltid företräde gentemot spårvagnar","option_b":"Spårvagnen har alltid företräde","option_c":"Högerregeln gäller","option_d":"Den som kör sakta ger företräde","correct":"B","explanation":"Spårvagnar har alltid företräde framför andra fordon om inte märken eller trafikljus anger annat."},
  {"category":"Korsningar","difficulty":"normal","question":"Du ska svänga vänster i en korsning. Vilken position ska du ha?","option_a":"Håll dig till höger","option_b":"Håll dig till vänster i körfältet","option_c":"Kör i mitten","option_d":"Positionen spelar ingen roll","correct":"B","explanation":"Vid vänstersväng håll dig till vänster i körfältet så mötande trafik kan passera på höger sida."},
  {"category":"Korsningar","difficulty":"easy","question":"Vad innebär en heldragen vit väjningslinje i en korsning?","option_a":"Stopplinje – du måste alltid stanna","option_b":"Markerar var du stanna om du måste ge företräde","option_c":"Markerar korsningens mitt","option_d":"Visar var cyklister får korsa","correct":"B","explanation":"En heldragen vit väjningslinje markerar var du stannar om du behöver ge ett annat fordon företräde. Du behöver inte stanna om vägen är klar."},
  {"category":"Korsningar","difficulty":"normal","question":"Varför är det viktigt att sakta ner tidigt vid en korsning?","option_a":"Det är ett lagkrav","option_b":"För att ha bättre sikt och tid att reagera","option_c":"Spara bränsle","option_d":"Det är bara rekommenderat","correct":"B","explanation":"Att sakta ner tidigt ger bättre sikt, tid att bedöma situationen och reagera vid oväntade händelser."},
  {"category":"Korsningar","difficulty":"normal","question":"I en korsning utan märken anländer fordon från alla fyra håll. Vem kör först?","option_a":"Den som anlänt sist","option_b":"Den som inte har något fordon till höger","option_c":"Det tyngsta fordonet","option_d":"Den som signalerar med horn","correct":"B","explanation":"Högerregeln gäller – du ger företräde till fordon från höger. Den utan fordon till höger kan köra."},

  # ── MÖTE & OMKÖRNING ──
  {"category":"Möte & Omkörning","difficulty":"easy","question":"Du möter ett fordon på en smal väg. Vad gör du?","option_a":"Tuta och kör förbi","option_b":"Backa till ett bredare ställe alltid","option_c":"Ge plats – kör till kanten och stanna vid behov","option_d":"Du har alltid företräde som uppåtkörande","correct":"C","explanation":"Visa hänsyn på smala vägar. Kör till kanten och stanna vid behov. I backe har det uppåtgående fordonet vanligtvis förrätten."},
  {"category":"Möte & Omkörning","difficulty":"normal","question":"Är det tillåtet att köra om ett fordon som väntar för att svänga vänster?","option_a":"Ja, alltid tillåtet på höger sida","option_b":"Nej, alltid förbjudet","option_c":"Ja, om det finns plats på höger sida och det är säkert","option_d":"Ja, men bara motorcyklar","correct":"C","explanation":"Du får köra om på höger sida ett fordon som väntar för att svänga vänster, om det är säkert och du inte kör utanför körbanan."},
  {"category":"Möte & Omkörning","difficulty":"normal","question":"Vad innebär en streckad gul mittlinje?","option_a":"Omkörning är alltid förbjudet","option_b":"Omkörning är tillåtet om det är säkert","option_c":"Bara tung trafik får köra om","option_d":"Gäller bara motorcyklar","correct":"B","explanation":"Streckade gula mittlinjer innebär att omkörning är tillåten om det är säkert – fri sikt, tillräckligt utrymme, inga fordon bakifrån."},
  {"category":"Möte & Omkörning","difficulty":"hard","question":"Du har påbörjat en omkörning men ser att det inte räcker. Vad ska du göra?","option_a":"Accelerera och genomför ändå","option_b":"Tuta och hoppas mötande hinner svänga","option_c":"Avbryt – fäll in bakom fordonet igen","option_d":"Bromsa hårt på möteskörbanan","correct":"C","explanation":"Avbryt direkt om du ser att omkörningen inte kan genomföras säkert. Fäll in bakom fordonet du höll på att köra om."},
  {"category":"Möte & Omkörning","difficulty":"easy","question":"Vad ska du kontrollera innan du börjar köra om?","option_a":"Bara att det finns fri sikt framåt","option_b":"Backspeglar, döda vinkeln och framåt","option_c":"Bara backspeglarna","option_d":"Att hastigheten är hög nog","correct":"B","explanation":"Innan omkörning: kontrollera backspeglar, den döda vinkeln och sikt framåt. Sätt på blinkers och säkerställ tid och plats."},
  {"category":"Möte & Omkörning","difficulty":"hard","question":"På motorväg med tre körfält – vilket körfält ska du normalt använda?","option_a":"Vänsterfältet","option_b":"Höger körfält – avvika bara för omkörning","option_c":"Mittenfilten","option_d":"Vilket som helst beroende på hastigheten","correct":"B","explanation":"Kör alltid i det högra körfältet och använd mitt- eller vänsterfältet bara för att köra om. Återgå till höger direkt efter."},
  {"category":"Möte & Omkörning","difficulty":"normal","question":"Är det tillåtet att köra om ett fordon i en korsning?","option_a":"Ja, om det är säkert","option_b":"Nej, det är förbjudet","option_c":"Ja, om du har förkörsrätt","option_d":"Ja, om inga märken förbjuder det","correct":"B","explanation":"Omkörning är förbjudet i korsningar och inom 20 meter från en korsning, om du inte befinner dig på en väg med körfält."},
  {"category":"Möte & Omkörning","difficulty":"normal","question":"Vilket avstånd är lämpligt till fordonet framför när du börjar köra om?","option_a":"Så nära som möjligt","option_b":"Normalt säkerhetsavstånd – ca 2-3 sekunders avstånd","option_c":"Minst 50 meter","option_d":"Minst 100 meter","correct":"B","explanation":"Håll normalt säkerhetsavstånd (2-3 sekunder). Kör inte för nära – du behöver se vägen framför om trafiken bromsar."},

  # ── HASTIGHET ──
  {"category":"Hastighet","difficulty":"easy","question":"Vad är normalhastigheten inne i en tätort om ingen annan hastighet är skyltad?","option_a":"30 km/h","option_b":"50 km/h","option_c":"70 km/h","option_d":"60 km/h","correct":"B","explanation":"Normalhastigheten i tätort är 50 km/h om ingen annan hastighet är skyltad. Zone 30 kan sänka det lokalt."},
  {"category":"Hastighet","difficulty":"normal","question":"Hur påverkas bromssträckan om du ökar hastigheten från 50 till 100 km/h?","option_a":"Fördubblas","option_b":"Trefaldigas","option_c":"Fyrfaldigas","option_d":"Ökar med 50%","correct":"C","explanation":"Bromssträckan ökar med kvadraten av hastighetsökningen. Dubblar du hastigheten (50→100) fyrfaldigas bromssträckan."},
  {"category":"Hastighet","difficulty":"easy","question":"Vad är maxhastigheten på en svensk motorväg om inget annat anges?","option_a":"90 km/h","option_b":"100 km/h","option_c":"110 km/h","option_d":"120 km/h","correct":"C","explanation":"Maxhastigheten på svenska motorvägar är 110 km/h om inget annat anges."},
  {"category":"Hastighet","difficulty":"hard","question":"Vad gäller för hastighetsgräns för ett tungt fordon (>3,5 ton) på landsväg?","option_a":"Samma som för personbil","option_b":"Max 80 km/h","option_c":"Max 90 km/h","option_d":"Max 70 km/h","correct":"B","explanation":"Tunga fordon (>3,5 ton) har maxhastighet 80 km/h på landsväg oavsett vad skylten visar för personbilar."},
  {"category":"Hastighet","difficulty":"normal","question":"Vad innebär 'rekommenderad hastighet' (gul skylt med siffra)?","option_a":"Obligatorisk maxhastighet","option_b":"Lämplig hastighet under normala förhållanden","option_c":"Minsta tillåtna hastighet","option_d":"Gäller bara tung trafik","correct":"B","explanation":"En gul hastighetsskylt visar rekommenderad hastighet. Det är inte lag, men avvikelse kan ses som oaktsamhet om olycka sker."},

  # ── MILJÖ & EKONOMI ──
  {"category":"Miljö & Ekonomi","difficulty":"easy","question":"Vad är det bästa sättet att minska bränsleförbrukning vid körning?","option_a":"Köra snabbt och bromsa sent","option_b":"Köra mjukt och förutseende","option_c":"Alltid köra på lägsta möjliga växel","option_d":"Undvika bromsarna","correct":"B","explanation":"Förutseende och mjuk körning minskar behovet av bromsning och acceleration. Håll ett jämnt flöde och planera rörelsen."},
  {"category":"Miljö & Ekonomi","difficulty":"normal","question":"Hur påverkar fel (för lågt) däcktryck bränsleförbrukning?","option_a":"Har ingen effekt","option_b":"Ökar rullmotståndet och förbrukningen","option_c":"Högt tryck ökar förbrukning","option_d":"Påverkar bara komfort","correct":"B","explanation":"För lågt däcktryck ökar rullmotståndet, vilket ger högre bränsleförbrukning och mer CO₂-utsläpp."},
  {"category":"Miljö & Ekonomi","difficulty":"normal","question":"Vad är den mest bränsleeffektiva hastigheten för en genomsnittlig personbil?","option_a":"60-80 km/h","option_b":"80-100 km/h","option_c":"50 km/h","option_d":"120 km/h","correct":"A","explanation":"De flesta personbilar är mest bränsleeffektiva vid 60-80 km/h. Ovanför 90 km/h ökar luftmotståndet exponentiellt."},
  {"category":"Miljö & Ekonomi","difficulty":"hard","question":"Varför kan det vara bättre för miljön att köra sin gamla bensinbil längre istället för att köpa en ny?","option_a":"Gamla bilar är alltid mer effektiva","option_b":"Tillverkning av ny bil skapar stora CO₂-utsläpp","option_c":"Nya bilar kräver mer service","option_d":"Bränsle är billigare i gamla bilar","correct":"B","explanation":"Tillverkning av en ny bil genererar stora mängder CO₂ ('gråa utsläpp'). Att köra befintlig bil längre kan ha lägre total klimatpåverkan."},
  {"category":"Miljö & Ekonomi","difficulty":"easy","question":"Vad innebär eco-körning?","option_a":"Att köra så snabbt som möjligt","option_b":"Mjuka accelerationer, tidig växling och förutseende körning","option_c":"Att alltid använda neutralläge i backar","option_d":"Att undvika motorvägar","correct":"B","explanation":"Eco-körning innebär mjuka accelerationer, tidig uppväxling och förutseende körning – minimera bromsning och onödiga gaspådrag."},

  # ── ALKOHOL & DROGER ──
  {"category":"Alkohol & Droger","difficulty":"easy","question":"Vad är promillegränsen för rattfylleri i Sverige?","option_a":"0,5 promille","option_b":"0,3 promille","option_c":"0,2 promille","option_d":"1,0 promille","correct":"C","explanation":"I Sverige är det rattfylleri att köra med 0,2 promille eller mer i blodet. Vid 1,0 promille är det grovt rattfylleri."},
  {"category":"Alkohol & Droger","difficulty":"normal","question":"Hur länge kan ett glas vin (1,5 dl, 12%) påverka körförmågan?","option_a":"Ca 30 minuter","option_b":"Ca 1 timme","option_c":"Ca 2-3 timmar","option_d":"Ca 6 timmar","correct":"C","explanation":"Kroppen bryter ned alkohol med ca 0,1 promille per timme. Ett glas vin tar 2-3 timmar att bryta ner. Det säkraste är att inte dricka alls om du ska köra."},
  {"category":"Alkohol & Droger","difficulty":"normal","question":"Vad innebär nolltolerans för narkotika i trafiken?","option_a":"Bötesstraff vid 5 nanogram/ml","option_b":"Varje påvisbar mängd narkotika i blodet är olaglig","option_c":"Gäller bara heroin och kokain","option_d":"Gäller bara yrkesförare","correct":"B","explanation":"Nolltolerans innebär att varje mätbar mängd narkotikaklassade substanser i blodet är olaglig vid körning."},
  {"category":"Alkohol & Droger","difficulty":"easy","question":"Varför är det extra farligt att kombinera alkohol med sömnmedel och köra?","option_a":"De tar ut varandra","option_b":"Effekterna förstärker varandra kraftigt","option_c":"Sömnmedel tar bort alkoholens effekt","option_d":"Det är lagligt om det är lite av varje","correct":"B","explanation":"Alkohol och sömnmedel förstärker varandras effekter dramatiskt, med kraftigt försämrad reaktionstid och koncentration."},
  {"category":"Alkohol & Droger","difficulty":"normal","question":"Vad händer om du vägrar blåsa i polisens alkotest?","option_a":"Ingenting, det är frivilligt","option_b":"Du döms som om du hade 0,5 promille","option_c":"Polisen kan kräva blodprov, och vägran behandlas som försvårande","option_d":"Du får en varning","correct":"C","explanation":"Om du vägrar alkotest kan polisen kräva blodprov. Att vägra båda behandlas som försvårande och kan ge strängare straff."},

  # ── SÄKERHET & UTRUSTNING ──
  {"category":"Säkerhet & Utrustning","difficulty":"easy","question":"Hur ska ett säkerhetsbälte bäras korrekt?","option_a":"Löst för komforten","option_b":"Tätt mot kroppen, diagonalt över bröstet och horisontellt över höfterna","option_c":"Bara om framstolarna är inkopplade","option_d":"Frivilligt under 50 km/h","correct":"B","explanation":"Säkerhetsbältet ska sitta tätt. Diagonalt band över bröstet (inte halsen) och höftbandet lågt över höften (inte magen)."},
  {"category":"Säkerhet & Utrustning","difficulty":"normal","question":"Vad är syftet med nackstödet i en bil?","option_a":"Komfort vid längre körning","option_b":"Minska whiplashskada vid kollision bakifrån","option_c":"Stöd vid bromsning","option_d":"Obligatorisk utrustning utan specifikt syfte","correct":"B","explanation":"Nackstödet minskar whiplash-skador vid påkörning bakifrån. Toppen ska vara i nivå med eller ovanför ögonhöjd."},
  {"category":"Säkerhet & Utrustning","difficulty":"easy","question":"Vad ska du regelbundet kontrollera i bilen?","option_a":"Bromsvätska och kylarvätska en gång per år","option_b":"Däcktryck, olja, kylvätska och vindrutetorkarvätska","option_c":"Bara bränslenivån","option_d":"Bara däcken en gång per månad","correct":"B","explanation":"Regelbundna kontroller minskar risken för olyckor. Viktiga: däcktryck, motoroljenivå, kylvätska och bromsvätska."},
  {"category":"Säkerhet & Utrustning","difficulty":"normal","question":"Vad ska du göra om din airbag-lampa lyser permanent?","option_a":"Det är normalt, ignorera det","option_b":"Kör försiktigt tills den slocknar","option_c":"Sök verkstad – airbagen kan vara ur funktion","option_d":"Täck över lampan","correct":"C","explanation":"En tänd airbag-varningslampa indikerar fel i krockkuddssystemet. Bilen kan vara sämre skyddad vid kollision. Sök verkstad."},
  {"category":"Säkerhet & Utrustning","difficulty":"hard","question":"Vad gör ABS-systemet vid hård inbromsning?","option_a":"Minskar bromskraften automatiskt","option_b":"Hindrar hjulen från att låsa sig","option_c":"Ökar bromskraften","option_d":"Aktiverar handbromsen","correct":"B","explanation":"ABS (Anti-lock Braking System) hindrar hjulen från att låsa sig vid hård inbromsning, vilket ger bättre styrbarhet och kortare bromssträcka."},

  # ── MÖRKER & SIKT ──
  {"category":"Mörker & Sikt","difficulty":"easy","question":"Hur långt lyser halvljuset normalt på en personbil?","option_a":"Ca 20-30 meter","option_b":"Ca 40-60 meter","option_c":"Ca 100 meter","option_d":"Ca 150 meter","correct":"B","explanation":"Halvljuset lyser normalt 40-60 meter framåt. Det räcker för hastigheter upp till ca 80 km/h."},
  {"category":"Mörker & Sikt","difficulty":"normal","question":"Vad ska du göra om mötande bil inte bländar ner sina helljus?","option_a":"Blinka med helljus tillbaka","option_b":"Titta mot vägkanten, sakta ner och håll kursen","option_c":"Stanna omedelbart","option_d":"Blunda kortare stunder","correct":"B","explanation":"Titta mot den högra vägkanten. Sakta ner och håll kursen längs kanten. Vänta tills bländningen upphör."},
  {"category":"Mörker & Sikt","difficulty":"normal","question":"När ska du använda dimljus?","option_a":"Alltid i mörker","option_b":"Vid dimma, snöfall eller regn som kraftigt begränsar sikten","option_c":"Bara på motorväg","option_d":"Som komplement till helljus alltid","correct":"B","explanation":"Dimljus ska användas när sikten är kraftigt nedsatt. Det är förbjudet att köra med dimljus utan nedsatt sikt – det bländar andra."},
  {"category":"Mörker & Sikt","difficulty":"hard","question":"Vad innebär 'överhastighet i förhållande till ljuskäglan'?","option_a":"Att köra snabbare än hastighetsgränsen","option_b":"Att köra så fort att du inte kan stanna inom den upplysta sträckan","option_c":"Att ha helljus på i stad","option_d":"Att köra utan ljus","correct":"B","explanation":"Om ett hinder dyker upp i utkanten av ditt halvljus och du inte hinner stanna – du kör för fort i förhållande till sikten. Vid 90 km/h är halvljuset (60 m) ofta otillräckligt."},

  # ── VÄGLAG & BROMSSTRÄCKA ──
  {"category":"Väglag & Bromssträcka","difficulty":"normal","question":"Hur mycket längre är bromssträckan på is jämfört med torr asfalt?","option_a":"Dubbelt","option_b":"Tre gånger","option_c":"5-10 gånger","option_d":"Lika med vinterdäck","correct":"C","explanation":"Bromssträckan på is kan vara 5-10 gånger längre än på torr asfalt. Vinterdäck förbättrar bromsen men eliminerar inte risken."},
  {"category":"Väglag & Bromssträcka","difficulty":"normal","question":"Vad är aquaplaning och hur undviker du det?","option_a":"Bilen glider på is – undvik med vinterdäck","option_b":"Däcken lyfter på vattenfilm – sänk hastigheten","option_c":"Bilen suger sig fast i vått underlag","option_d":"Kylsystemet överhettas","correct":"B","explanation":"Aquaplaning uppstår när ett vattenfilmsskikt bildas under däcken och de förlorar greppet. Sänk hastigheten vid vattenpölar och ha däck med bra mönsterdjup."},
  {"category":"Väglag & Bromssträcka","difficulty":"hard","question":"Vad bör du göra om bilens bak börjar glida ut i en kurva på halt underlag?","option_a":"Bromsa hårt och styr rakt","option_b":"Styr mot glidriktningen och ta av foten från gasen","option_c":"Accelerera ur kurvan","option_d":"Gasa och styr mot vägkanten","correct":"B","explanation":"Ta foten från gasen och styr i glidriktningen (motvänd) för att räta upp bilen. Broms inte hårt – det förvärrar glidet. Lugna rörelser är nyckeln."},
]

headers = {
    "Content-Type": "application/json",
    "apikey": KEY,
    "Authorization": f"Bearer {KEY}",
    "Prefer": "return=minimal"
}

batch_size = 10
ok = 0
errors = []

for i in range(0, len(QUESTIONS), batch_size):
    batch = QUESTIONS[i:i+batch_size]
    body = json.dumps(batch).encode()
    req = urllib.request.Request(URL, data=body, headers=headers, method="POST")
    try:
        with urllib.request.urlopen(req) as resp:
            ok += len(batch)
            print(f"Batch {i//batch_size + 1}: {len(batch)} frågor insatta (total {ok})")
    except urllib.error.HTTPError as e:
        err = e.read().decode()
        errors.append(f"Batch {i//batch_size + 1}: {err[:200]}")
        print(f"FEL batch {i//batch_size + 1}: {err[:200]}")

print(f"\nKlart! {ok}/{len(QUESTIONS)} frågor insatta.")
if errors:
    print("Fel:", errors)
