#!/usr/bin/env python3
"""Insert Swedish driving theory questions into Supabase."""
import json, urllib.request, sys

SUPABASE_URL = "https://mnmotdluigzeehdjbhbu.supabase.co"
ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ubW90ZGx1aWd6ZWVoZGpiaGJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzMzcwODQsImV4cCI6MjA4NTkxMzA4NH0.pEV4zBWqxnrPVyvrenPVArXxvXr1eRU1eRaXhl7AIY8"

QUESTIONS = [
  # VÄGMÄRKEN
  {"category":"Vägmärken","difficulty":"easy","question":"Vad betyder ett rött åttkantigt märke med texten STOP?","option_a":"Du ska sakta ner","option_b":"Du ska stanna och lämna företräde åt all trafik","option_c":"Du ska stanna i 3 sekunder","option_d":"Du ska blinka och köra om","correct":"B","explanation":"STOP-skylten (märke B1) innebär att du ska stanna helt vid stopplinje och lämna företräde åt all trafik på korsande väg."},
  {"category":"Vägmärken","difficulty":"easy","question":"Vad betyder en vit triangel med spetsen nedåt på vägbanan?","option_a":"Väjningsplikt","option_b":"Stopplikt","option_c":"Gångbana framåt","option_d":"Farlig korsning","correct":"A","explanation":"En vit triangel med spetsen nedåt på vägbanan markerar väjningsplikt — du ska lämna företräde åt korsande trafik."},
  {"category":"Vägmärken","difficulty":"normal","question":"Vad innebär märket 'Väjningsplikt mot mötande fordon'?","option_a":"Du har företräde framför mötande fordon","option_b":"Du ska stanna och vänta tills mötande fordon passerat","option_c":"Du ska köra i 30 km/h","option_d":"Mötande fordon har företräde och du ska väja","correct":"D","explanation":"Märket (B4) innebär att du ska lämna företräde åt mötande fordon, exempelvis vid en smal passage eller bro."},
  {"category":"Vägmärken","difficulty":"normal","question":"Vad innebär ett blått runt märke med en vit pil rakt upp?","option_a":"Parkering tillåten","option_b":"Obligatorisk körriktning — du måste köra rakt fram","option_c":"Upphörande av förbud","option_d":"Cykelbana","correct":"B","explanation":"Blå runda märken med vita pilar är påbudsmärken. Pil rakt upp innebär att du måste köra rakt fram."},
  {"category":"Vägmärken","difficulty":"hard","question":"Vad gäller vid märket 'Förbud mot fordonstrafik' (rött runt märke med röd horisontell balk)?","option_a":"Alla fordon förbjudna utom cyklar","option_b":"Alla motordrivna fordon förbjudna","option_c":"Alla fordon förbjudna i båda riktningarna","option_d":"Fordon tyngre än 3,5 ton förbjudna","correct":"C","explanation":"Märket C1 (förbud mot trafik i båda riktningarna) innebär att alla fordon är förbjudna att passera i båda riktningarna."},
  {"category":"Vägmärken","difficulty":"easy","question":"Vad betyder ett gult-rött rombformat märke på en väg?","option_a":"Skola framför","option_b":"Du befinner dig på en huvudled med företräde","option_c":"Farlig kurva","option_d":"Vägarbete","correct":"B","explanation":"Det gula rombformade märket markerar att du befinner dig på en prioriterad väg (huvudled) och har företräde i korsningar."},
  {"category":"Vägmärken","difficulty":"normal","question":"Vad innebär märket med siffran 3,8 och en bil med en pil nedåt?","option_a":"Hastighetsgränsen är 3,8 km/h","option_b":"Fordon högre än 3,8 meter är förbjudna","option_c":"Bron tål max 3,8 ton","option_d":"Vägen slutar om 3,8 km","correct":"B","explanation":"Märket anger maximal tillåten fordonshöjd. Fordon eller last som är högre än 3,8 meter får inte passera."},
  {"category":"Vägmärken","difficulty":"normal","question":"Vad betyder ett rödrandat trekantigt märke med ett lok?","option_a":"Järnvägsövergång med bom","option_b":"Järnvägsövergång utan bom","option_c":"Vägkorsning med spårväg","option_d":"Varning för kollision","correct":"B","explanation":"Det trekantiga märket med lok (A35) varnar för en obevakad järnvägsövergång utan bommar — var extra försiktig."},
  {"category":"Vägmärken","difficulty":"hard","question":"Vad innebär ett grönt märke med en vit motorvägssymbol?","option_a":"Motortrafikled börjar","option_b":"Motorväg börjar — speciella regler gäller","option_c":"Rekommenderad hastighet 110 km/h","option_d":"Omkörning förbjuden upphör","correct":"B","explanation":"Det gröna märket med motorvägssymbol markerar att motorväg börjar. Mopeder, cyklar och långsamtgående fordon är förbjudna."},
  {"category":"Vägmärken","difficulty":"easy","question":"Vad betyder ett rödrandat trekantigt märke med en figur som faller?","option_a":"Varning för vilt","option_b":"Varning för halt väglag","option_c":"Varning för barn","option_d":"Varning för fotgängare","correct":"D","explanation":"Märket A19 varnar för platser där fotgängare ofta korsar vägen, t.ex. nära skolor eller köpcentrum."},
  {"category":"Vägmärken","difficulty":"normal","question":"Vad innebär ett märke med texten 'ZONE 30' i rött?","option_a":"Rekommenderad hastighet 30 km/h i zonen","option_b":"Hastighetsgränsen 30 km/h gäller i hela zonen tills den avslutas","option_c":"Skolzon, 30 km/h gäller bara på dagtid","option_d":"Minsta hastighet 30 km/h","correct":"B","explanation":"En 30-zon innebär att 30 km/h gäller i hela zonen tills du ser det avslutande märket, utan att nya skyltar behövs på varje gata."},
  {"category":"Vägmärken","difficulty":"hard","question":"Vad innebär ett blått rektangulärt märke med texten 'P' och en siffra?","option_a":"Parkeringsförbud i X timmar","option_b":"Parkering tillåten med tidsbegränsning i X timmar","option_c":"Parkering tillåten utan begränsning","option_d":"Parkeringshus X meter bort","correct":"B","explanation":"Det blå P-märket med siffra anger att parkering är tillåten men tidsbegränsad. Du behöver ofta använda en parkeringsskiva."},
  {"category":"Vägmärken","difficulty":"easy","question":"Vad varnar ett rödrandat trekantigt märke med en rak linje för?","option_a":"Stigning","option_b":"Ojämn väg","option_c":"Brant utförsbacke","option_d":"Farlig vägsida","correct":"B","explanation":"Märket A13 (ojämn väg) varnar för en vägsträcka med ojämnheter, gropar eller stötiga partier."},

  # TRAFIKREGLER
  {"category":"Trafikregler","difficulty":"easy","question":"Vad gäller om du kör på en väg utan hastighetsskylt utanför tättbebyggt område?","option_a":"70 km/h","option_b":"90 km/h","option_c":"110 km/h","option_d":"80 km/h","correct":"B","explanation":"Utanför tättbebyggt område gäller 70 km/h som bashastighet, men de flesta landsvägar har 90 km/h som generell gräns om inget annat anges."},
  {"category":"Trafikregler","difficulty":"easy","question":"När är du skyldig att använda bilbälte?","option_a":"Bara på motorväg","option_b":"Alltid när du sitter i en bil utrustad med bälte","option_c":"Bara som förare, inte passagerare","option_d":"Bara om du kör snabbare än 30 km/h","correct":"B","explanation":"Du är alltid skyldig att använda bilbälte i en bil utrustad med bälte, oavsett om du sitter fram eller bak."},
  {"category":"Trafikregler","difficulty":"normal","question":"Vad gäller för mobiltelefon under körning?","option_a":"Tillåtet i låg hastighet","option_b":"Tillåtet om du använder högtalarfunktion utan att hålla telefonen","option_c":"Förbjudet att hålla i handen under körning","option_d":"Tillåtet om du stannar vid trafikljus","correct":"C","explanation":"Det är förbjudet att hålla mobiltelefon i handen under körning. Handsfree utan att hålla telefonen är tillåtet."},
  {"category":"Trafikregler","difficulty":"normal","question":"Vem har företräde när du ska köra ut från en parkeringsplats till en vanlig väg?","option_a":"Du som lämnar parkeringen","option_b":"Trafiken på den väg du kör ut till","option_c":"Den som kom dit först","option_d":"Trafiken på vägen bara om det finns ett STOP-märke","correct":"B","explanation":"När du lämnar en parkeringsplats, gårdsgata eller bensinstation ska du alltid lämna företräde åt trafiken på den väg du kör ut till."},
  {"category":"Trafikregler","difficulty":"normal","question":"Hur långt från en korsning får du parkera?","option_a":"5 meter","option_b":"10 meter","option_c":"15 meter","option_d":"20 meter","correct":"B","explanation":"Du får inte parkera inom 10 meter från en korsning, för att inte skymma sikten för andra trafikanter."},
  {"category":"Trafikregler","difficulty":"easy","question":"Vad ska du göra om ett utryckningsfordon med blåljus och siren närmar sig?","option_a":"Köra snabbare för att komma ur vägen","option_b":"Stanna omedelbart oavsett var du befinner dig","option_c":"Lämna fri väg och stanna vid sidan om möjligt","option_d":"Fortsätta köra normalt","correct":"C","explanation":"Du ska lämna fri väg för utryckningsfordon och vid behov stanna. Stanna inte på ett farligt ställe."},
  {"category":"Trafikregler","difficulty":"normal","question":"Vad gäller för cyklister vid ett övergångställe?","option_a":"Cyklister har alltid företräde","option_b":"Cyklister ska stiga av och leda cykeln för att använda övergångsstället","option_c":"Cyklister får cykla över om det är grönt","option_d":"Cyklister har samma rättigheter som fotgängare vid övergångsstället","correct":"B","explanation":"Vid ett övergångställe ska cyklister stiga av och leda cykeln. Cyklister har ingen automatisk rätt att cykla över, såvida det inte är en cykelöverfart."},
  {"category":"Trafikregler","difficulty":"hard","question":"Vad gäller om du kör på en gårdsgata?","option_a":"Max 10 km/h och fotgängare har alltid företräde","option_b":"Max 30 km/h, vanliga trafikregler gäller","option_c":"Max 10 km/h, fordon har företräde","option_d":"Max 20 km/h och du får inte parkera","correct":"A","explanation":"På en gårdsgata gäller max 10 km/h och fotgängare har alltid företräde. Fordon som lämnar gårdsgatan ska lämna företräde åt annan trafik."},
  {"category":"Trafikregler","difficulty":"normal","question":"Var är det förbjudet att stanna?","option_a":"Utanför ett hus","option_b":"I en korsning eller nära korsning om det hindrar trafiken","option_c":"På en parkeringsficka","option_d":"Bredvid en annan bil","correct":"B","explanation":"Det är förbjudet att stanna i en korsning, på en spärrlinje, på en busshållplats, och på andra platser där det hindrar trafiken eller är farligt."},
  {"category":"Trafikregler","difficulty":"easy","question":"Hur nära ett övergångställe får du parkera?","option_a":"5 meter","option_b":"10 meter","option_c":"15 meter","option_d":"20 meter","correct":"B","explanation":"Du får inte parkera inom 10 meter framför ett övergångställe. Det gäller för att inte skymma sikten för fotgängare och förare."},
  {"category":"Trafikregler","difficulty":"hard","question":"Vad innebär ett halvt vitt streck (underbrutet) på vägbanan?","option_a":"Stopplinje","option_b":"Körfältsavgränsning — du får byta körfält om det är säkert","option_c":"Mittlinje — du får inte korsa den","option_d":"Cykelfält","correct":"B","explanation":"Underbruten (streckad) linje är en körfälts- eller vägavgränsning. Du får byta körfält om det är säkert. Heldragen linje får inte korsas."},
  {"category":"Trafikregler","difficulty":"normal","question":"Vad gäller om du möter en skolbuss med blinkande orange ljus som stått stilla?","option_a":"Kör förbi försiktigt","option_b":"Stanna och vänta tills bussen kört iväg eller ljusen slocknat","option_c":"Tuta för att varna barnen","option_d":"Ingen speciell regel gäller","correct":"B","explanation":"När en skolbuss har blinkande orange varningsljus och stått stilla ska du stanna och invänta att bussen kört iväg eller ljusen slocknat. Barn kan springa ut."},

  # KORSNINGAR
  {"category":"Korsningar","difficulty":"easy","question":"Du ska svänga vänster i en korsning. En mötande bil kör rakt fram. Vem har företräde?","option_a":"Du som svänger vänster","option_b":"Den mötande bilen som kör rakt fram","option_c":"Den som kom till korsningen först","option_d":"Det beror på om det finns skyltar","correct":"B","explanation":"När du svänger vänster i en korsning ska du alltid lämna företräde åt mötande fordon som kör rakt fram eller svänger höger."},
  {"category":"Korsningar","difficulty":"normal","question":"I en korsning utan skyltar möter du en bil från vänster. Vem har företräde?","option_a":"Du","option_b":"Bilen från vänster","option_c":"Den som kör fortast","option_d":"Den som signalerar med horn","correct":"A","explanation":"I en korsning utan skyltar gäller högerregeln. Bilen från vänster ska lämna företräde åt dig, som befinner dig till höger om den bilen."},
  {"category":"Korsningar","difficulty":"normal","question":"Vad innebär 'zipper-principen' vid en avsmalnande körfil?","option_a":"Du ska bromsa kraftigt och stanna","option_b":"Fordonen turas om att foga in, ett i taget","option_c":"Det fordon som är längst fram har alltid företräde","option_d":"Det är förbjudet att byta körfil","correct":"B","explanation":"Vid avsmalnande körfil ska fordonen turas om att foga in i det kvarvarande körfältet — ett från varje körfält, som en dragkedja."},
  {"category":"Korsningar","difficulty":"hard","question":"Du kör på en huvudled. En bil kommer från höger på en mindre väg. Vem har företräde?","option_a":"Bilen från höger (högerregeln)","option_b":"Du på huvudleden","option_c":"Det beror på hastighetsgränsen","option_d":"Den som kom till korsningen först","correct":"B","explanation":"På en huvudled (markerad med gult rombmärke) har du företräde framför trafik från korsande vägar, även om de kommer från höger."},
  {"category":"Korsningar","difficulty":"easy","question":"Vad ska du göra vid ett rött ljus i en trafikljuskorsning?","option_a":"Sakta ner och fortsätta om det är säkert","option_b":"Stanna vid stopplinjen","option_c":"Blinka och stanna","option_d":"Stanna bara om det finns fotgängare","correct":"B","explanation":"Vid rött ljus ska du stanna vid stopplinjen. Du får inte köra förrän det blivit grönt."},
  {"category":"Korsningar","difficulty":"hard","question":"Vad innebär blinkande gult ljus i en trafikljussignal?","option_a":"Kör igenom snabbt","option_b":"Stanna — det är samma som rött","option_c":"Kör med försiktighet och lämna företräde vid behov","option_d":"Signalen är trasig, kör inte","correct":"C","explanation":"Blinkande gult ljus innebär att du ska köra försiktigt och observera trafiken. Lämna företräde där det krävs enligt trafikreglerna."},
  {"category":"Korsningar","difficulty":"normal","question":"Du ska köra in i en rondell. Vem har företräde?","option_a":"Du som ska köra in","option_b":"Trafiken som redan finns i rondellen","option_c":"Fordon från höger i rondellen","option_d":"Det beror på hastighetsgränsen","correct":"B","explanation":"I en cirkulationsplats (rondell) har trafiken som redan kör i rondellen företräde. Du som ska köra in lämnar företräde."},
  {"category":"Korsningar","difficulty":"normal","question":"Hur signalerar du att du ska svänga höger?","option_a":"Blinka vänster","option_b":"Blinka höger i god tid innan svängen","option_c":"Använd horn","option_d":"Sänk hastigheten utan att blinka","correct":"B","explanation":"Du ska använda höger blinkers i god tid (minst 3 sekunder) innan du svänger höger, byter fil eller stannar till höger."},
  {"category":"Korsningar","difficulty":"hard","question":"Vad gäller om du vill svänga vänster och det finns en fil för vänstersväng?","option_a":"Du måste använda vänstersväng-filen","option_b":"Du väljer fritt vilken fil du vill använda","option_c":"Du ska köra rakt fram och svänga längre fram","option_d":"Du ska använda mittfilen","correct":"A","explanation":"Om det finns en separat fil för vänstersväng ska du använda den. Det skapar bättre trafikflöde och minskar risken för kollision."},

  # MÖTE & OMKÖRNING
  {"category":"Möte & Omkörning","difficulty":"easy","question":"Var är det absolut förbjudet att köra om?","option_a":"På rak väg","option_b":"Vid en kröken, backkrön eller på ett övergångställe","option_c":"På motorväg","option_d":"Utanför tättbebyggt område","correct":"B","explanation":"Det är förbjudet att köra om vid krökar, backkrön och övergångställen, eftersom risken för kollision är stor vid begränsad sikt."},
  {"category":"Möte & Omkörning","difficulty":"normal","question":"Vilket sidoavstånd rekommenderas när du kör om en cyklist?","option_a":"Minst 0,5 meter","option_b":"Minst 1 meter","option_c":"Minst 1,5 meter","option_d":"Minst 2 meter","correct":"C","explanation":"Du ska passera cyklister med minst 1,5 meters sidoavstånd, och helst 2 meter om möjligt, för att ge dem trygghet och utrymme."},
  {"category":"Möte & Omkörning","difficulty":"hard","question":"Du kör bakom en bil som håller på att köra om. Vad gäller för dig?","option_a":"Du får köra om bilen och det fordon den kör om","option_b":"Du ska hålla tillräckligt avstånd och inte påbörja omkörning förrän det är säkert","option_c":"Du ska blinka och signalera att du vill köra om","option_d":"Du ska öka hastigheten för att hinna med","correct":"B","explanation":"Om bilen framför kör om ska du hålla tillräckligt avstånd och vänta. Du får inte påbörja en omkörning som kan störa trafiksäkerheten."},
  {"category":"Möte & Omkörning","difficulty":"normal","question":"I vilket körfält ska du normalt köra på en flerfältsväg?","option_a":"Vänster körfält","option_b":"Höger körfält","option_c":"Vilket som helst","option_d":"Mittkörfältet","correct":"B","explanation":"Du ska normalt hålla höger körfält. Vänstra körfältet används för omkörning och man ska återvända till höger körfält efteråt."},
  {"category":"Möte & Omkörning","difficulty":"hard","question":"Vad innebär märket 'Omkörningsförbud'?","option_a":"Förbjudet att köra om cyklar och mopeder","option_b":"Förbjudet att köra om motorfordon med mer än 2 hjul","option_c":"Förbjudet att köra om alla fordon","option_d":"Förbjudet att köra om lastbilar","correct":"B","explanation":"Märket C38 (Omkörningsförbud) innebär att det är förbjudet att köra om motorfordon med mer än 2 hjul. Cyklar och mopeder kan fortfarande köras om."},
  {"category":"Möte & Omkörning","difficulty":"normal","question":"Vad ska du göra innan du påbörjar en omkörning?","option_a":"Tuta för att varna fordonet framför","option_b":"Kontrollera att vägen framåt är fri, att det är tillåtet, och blinka","option_c":"Öka hastigheten direkt","option_d":"Köra ut i mötande körfält och titta","correct":"B","explanation":"Innan omkörning ska du: kontrollera att det är fritt framåt, att det är tillåtet (inga förbud, bra sikt), blinka och kontrollera backspeglarna."},

  # HASTIGHET
  {"category":"Hastighet","difficulty":"easy","question":"Vad är hastighetsgränsen i ett tättbebyggt område om inget annat anges?","option_a":"30 km/h","option_b":"50 km/h","option_c":"60 km/h","option_d":"70 km/h","correct":"B","explanation":"Bashastigheten i tättbebyggt område är 50 km/h om inget annat anges med skyltar."},
  {"category":"Hastighet","difficulty":"easy","question":"Vad är hastighetsgränsen på en motorväg i Sverige om inget annat anges?","option_a":"100 km/h","option_b":"110 km/h","option_c":"120 km/h","option_d":"130 km/h","correct":"C","explanation":"Hastighetsgränsen på motorväg är 120 km/h om inget annat anges med skyltar."},
  {"category":"Hastighet","difficulty":"normal","question":"Du kör i 90 km/h. Hur lång är din reaktionssträcka om reaktionstiden är 1 sekund?","option_a":"15 meter","option_b":"20 meter","option_c":"25 meter","option_d":"30 meter","correct":"C","explanation":"I 90 km/h kör du 25 meter per sekund (90 ÷ 3,6 = 25 m/s). Med 1 sekunds reaktionstid är reaktionssträckan 25 meter."},
  {"category":"Hastighet","difficulty":"hard","question":"Hur förändras bromssträckan om du dubblar din hastighet?","option_a":"Den dubblas","option_b":"Den tredubblas","option_c":"Den fyradubblas","option_d":"Den sexdubblas","correct":"C","explanation":"Bromssträckan ökar med kvadraten på hastigheten. Om du dubblar hastigheten fyradubblas bromssträckan (2² = 4)."},
  {"category":"Hastighet","difficulty":"normal","question":"Vad är maxhastigheten för en tung lastbil (över 3,5 ton) utanför tättbebyggt område?","option_a":"70 km/h","option_b":"80 km/h","option_c":"90 km/h","option_d":"Samma som personbilar","correct":"B","explanation":"Tunga lastbilar (totalvikt över 3,5 ton) har en maxhastighet på 80 km/h på landsväg, om inte lägre gräns gäller."},
  {"category":"Hastighet","difficulty":"normal","question":"Du kör 50 km/h. Ungefär hur lång är den totala stoppsträckan under normala förhållanden?","option_a":"20 meter","option_b":"35 meter","option_c":"50 meter","option_d":"70 meter","correct":"B","explanation":"I 50 km/h är reaktionssträckan ca 14 m och bromssträckan ca 20 m, totalt ca 35 meter på torr asfalt."},
  {"category":"Hastighet","difficulty":"easy","question":"Vad innebär en skylt med siffran '30' inskriven i en röd cirkel?","option_a":"Rekommenderad hastighet 30 km/h","option_b":"Hastighetsgränsen är 30 km/h","option_c":"Minsta hastighet 30 km/h","option_d":"Tillfällig hastighetsbegränsning","correct":"B","explanation":"En röd hastighetsskylt (C31) innebär att hastighetsgränsen är 30 km/h — det är ett obligatoriskt förbud, inte en rekommendation."},
  {"category":"Hastighet","difficulty":"hard","question":"Vilken hastighetsgräns gäller normalt på en motortrafikled?","option_a":"90 km/h","option_b":"100 km/h","option_c":"110 km/h","option_d":"120 km/h","correct":"C","explanation":"På motortrafikled gäller normalt 110 km/h om inte annat anges. Motortrafikled är en väg med begränsat tillträde men utan fullständig mitträcke som motorväg."},

  # MILJÖ & EKONOMI
  {"category":"Miljö & Ekonomi","difficulty":"easy","question":"Vilket körsätt minskar bränsleförbrukningen mest?","option_a":"Hård acceleration och tidig bromsning","option_b":"Jämn hastighet, tidig växling och förutseende körning","option_c":"Hög motorvarvtal hela tiden","option_d":"Undvika att använda bromsen","correct":"B","explanation":"Förutseende körning med jämn hastighet och tidig växling till högre växel minskar bränsleförbrukningen avsevärt."},
  {"category":"Miljö & Ekonomi","difficulty":"normal","question":"Hur påverkar för lågt däcktryck bränsleförbrukningen?","option_a":"Det spelar ingen roll","option_b":"Lägre tryck ger lägre rullmotstånd och lägre förbrukning","option_c":"För lågt tryck ökar rullmotståndet och bränsleförbrukningen","option_d":"För lågt tryck ger bättre grepp och lägre förbrukning","correct":"C","explanation":"För lågt däcktryck ökar rullmotståndet vilket leder till högre bränsleförbrukning och ökat slitage."},
  {"category":"Miljö & Ekonomi","difficulty":"easy","question":"Vad bör du göra om du ska stå stilla mer än ca 1 minut med motorn igång?","option_a":"Öka varvtalet för att ladda batteriet","option_b":"Stänga av motorn för att spara bränsle och minska utsläpp","option_c":"Byta till neutralläge","option_d":"Ingenting — modern bränsleinsprutning är effektiv","correct":"B","explanation":"Om du stannar mer än ca 1 minut bör du stänga av motorn. Det sparar bränsle och minskar onödiga avgasutsläpp."},
  {"category":"Miljö & Ekonomi","difficulty":"hard","question":"Vilken körstil ger lägst CO₂-utsläpp per kilometer?","option_a":"Hög hastighet på motorväg","option_b":"Stadskörning med täta starter och stopp","option_c":"Jämn hastighet runt 80–90 km/h","option_d":"Körning i lägsta möjliga växel","correct":"C","explanation":"Jämn hastighet runt 80–90 km/h är den mest bränsleeffektiva körstilen. Hög hastighet ökar luftmotståndet och stadskörning med täta stopp är ineffektivt."},
  {"category":"Miljö & Ekonomi","difficulty":"normal","question":"Vad innebär 'eco-körning'?","option_a":"Körning utan AC och radio","option_b":"Förutseende körning, tidig växling och undvikande av onödig acceleration","option_c":"Körning med lägre hastighet än hastighetsgränsen alltid","option_d":"Att alltid köra i lägsta varvtal oavsett situation","correct":"B","explanation":"Eco-körning innebär förutseende körning med tidig uppväxling, jämn hastighet och undvikande av onödig acceleration och bromsning."},

  # ALKOHOL & DROGER
  {"category":"Alkohol & Droger","difficulty":"easy","question":"Vad är gränsen för rattfylleri i Sverige?","option_a":"0,5 promille","option_b":"0,2 promille","option_c":"0,8 promille","option_d":"1,0 promille","correct":"B","explanation":"I Sverige är gränsen för rattfylleri 0,2 promille. Grovt rattfylleri gäller från 1,0 promille eller om körförmågan är påtagligt nedsatt."},
  {"category":"Alkohol & Droger","difficulty":"normal","question":"Hur snabbt bryts alkohol ned i kroppen?","option_a":"0,5 promille per timme","option_b":"0,1–0,15 promille per timme","option_c":"1 promille per timme","option_d":"Det beror enbart på vad du åt","correct":"B","explanation":"Alkohol bryts ned med ca 0,1–0,15 promille per timme. Exakt hastighet varierar individuellt och kan inte påskyndas med kaffe eller motion."},
  {"category":"Alkohol & Droger","difficulty":"normal","question":"Vad är straffet för grovt rattfylleri i Sverige?","option_a":"Böter","option_b":"Fängelse i upp till 6 månader","option_c":"Fängelse i upp till 2 år","option_d":"Körkortsindragning i 1 år","correct":"C","explanation":"Grovt rattfylleri kan ge fängelse i upp till 2 år, körkortsindragning och villkorlig dom eller samhällstjänst."},
  {"category":"Alkohol & Droger","difficulty":"easy","question":"Hur påverkar alkohol körförmågan?","option_a":"Förbättrar reaktionstiden","option_b":"Försämrar omdöme, reaktionstid och koordination","option_c":"Påverkar bara synen, inte reaktionstiden","option_d":"Påverkar inte körförmågan i låga doser","correct":"B","explanation":"Alkohol försämrar omdöme, reaktionstid, koordination och syn redan i låga doser. Risken för trafikolycka ökar kraftigt."},
  {"category":"Alkohol & Droger","difficulty":"hard","question":"Vad gäller om polis misstänker att du kör påverkad av narkotika?","option_a":"De kan bara ta blodprov","option_b":"De kan göra ett beteendetest och kräva urin- eller blodprov","option_c":"De behöver observera dig i 30 minuter","option_d":"De måste ha ett vittne","correct":"B","explanation":"Polisen kan göra ett fältnykterhetstest (beteendekontroll) och kräva urin- eller blodprov vid misstanke om narkotikapåverkan."},
  {"category":"Alkohol & Droger","difficulty":"normal","question":"Vilka läkemedel kan göra det olagligt att köra bil?","option_a":"Bara sömnmedel","option_b":"Alla receptbelagda läkemedel","option_c":"Läkemedel som påverkar reaktionstid, koncentration eller omdöme","option_d":"Inga läkemedel, bara alkohol och narkotika räknas","correct":"C","explanation":"Läkemedel som påverkar din förmåga att köra — exempelvis starka smärtstillare, sömnmedel eller antihistaminer — kan göra det olagligt och farligt att köra."},

  # SÄKERHET & UTRUSTNING
  {"category":"Säkerhet & Utrustning","difficulty":"easy","question":"Vad ska en bil alltid ha med sig enligt lag i Sverige?","option_a":"Brandsläckare och förstahjälpenkit","option_b":"Varningstriangel och reflexväst","option_c":"Varningstriangel","option_d":"Förstahjälpenkit","correct":"C","explanation":"I Sverige är varningstriangel obligatorisk i alla personbilar. Reflexväst rekommenderas men är inte lagstadgad."},
  {"category":"Säkerhet & Utrustning","difficulty":"normal","question":"Hur långt bak ska du placera varningstriangeln vid ett stopp på landsväg?","option_a":"Minst 30 meter","option_b":"Minst 50 meter","option_c":"Minst 100 meter","option_d":"Minst 150 meter","correct":"C","explanation":"På landsväg utanför tättbebyggt område ska varningstriangeln placeras minst 100 meter bakom fordonet."},
  {"category":"Säkerhet & Utrustning","difficulty":"normal","question":"Vad gäller för barn under 135 cm i en bil?","option_a":"Bälteskudde räcker alltid","option_b":"De måste sitta i en godkänd bilbarnstol anpassad för deras storlek","option_c":"De får inte sitta i framsätet","option_d":"De ska alltid sitta bakåtvänd","correct":"B","explanation":"Barn under 135 cm ska använda ett godkänt fordonsbarnsskydd anpassat för deras storlek och vikt."},
  {"category":"Säkerhet & Utrustning","difficulty":"easy","question":"Vad ska du kontrollera på däcken regelbundet?","option_a":"Bara mönsterdjupet","option_b":"Trycket, mönsterdjupet och skicket","option_c":"Bara trycket","option_d":"Bara om det läcker luft","correct":"B","explanation":"Du ska regelbundet kontrollera däcktrycket, mönsterdjupet (minst 1,6 mm för sommardäck) och att däcken inte har sprickor."},
  {"category":"Säkerhet & Utrustning","difficulty":"normal","question":"När är vinterdäck obligatoriskt i Sverige?","option_a":"1 december till 31 mars","option_b":"1 november till 31 mars","option_c":"Vid vinterväglag (snö, is, slask) oavsett datum","option_d":"Från den dag det snöar","correct":"C","explanation":"Vinterdäck är obligatoriskt vid vinterväglag (is, snö, slask, frost). Det finns ingen fast datumregel."},
  {"category":"Säkerhet & Utrustning","difficulty":"hard","question":"Vad är minimalt lagstadgat mönsterdjup för vinterdäck i Sverige?","option_a":"1,6 mm","option_b":"2 mm","option_c":"3 mm","option_d":"Det finns inget krav för vinterdäck","correct":"C","explanation":"Vinterdäck ska ha minst 3 mm mönsterdjup för att vara effektiva. Transportstyrelsen kräver detta vid vinterväglag."},
  {"category":"Säkerhet & Utrustning","difficulty":"normal","question":"Vad ska du kontrollera i motorhuven regelbundet?","option_a":"Bara oljenivån","option_b":"Olja, kylarvätska, bromsvätska och vindrutespolvätska","option_c":"Bara kylarvätska och olja","option_d":"Ingenting — modern bil sköter sig själv","correct":"B","explanation":"Du ska regelbundet kontrollera motorolja, kylarvätska, bromsvätska och vindrutespolvätska för att undvika skador och trafikfarliga situationer."},

  # MÖRKER & SIKT
  {"category":"Mörker & Sikt","difficulty":"easy","question":"Vilket ljus ska du använda när du möter ett fordon i mörker?","option_a":"Helljus","option_b":"Halvljus (mötesljus)","option_c":"Parkeringsljus","option_d":"Inga ljus behövs","correct":"B","explanation":"Du ska byta till halvljus (mötesljus) när du möter ett fordon i mörker, för att inte blända den mötande föraren."},
  {"category":"Mörker & Sikt","difficulty":"normal","question":"På vilket avstånd ska du senast byta till halvljus när du möter ett fordon?","option_a":"100 meter","option_b":"150 meter","option_c":"200 meter","option_d":"250 meter","correct":"C","explanation":"Du ska senast byta till halvljus när du möter ett fordon på 200 meters avstånd för att inte blända föraren."},
  {"category":"Mörker & Sikt","difficulty":"normal","question":"Vad ska du göra om du bländas av ett mötande fordon i mörker?","option_a":"Tuta och blinka med helljuset","option_b":"Titta bort mot höger vägkant och sakta ner","option_c":"Stänga ögonen tillfälligt","option_d":"Öka hastigheten för att snabbt passera","correct":"B","explanation":"Om du bländas ska du titta mot höger vägkant och sakta ner. Stirra inte in i ljuset."},
  {"category":"Mörker & Sikt","difficulty":"hard","question":"Vad gäller om sikten är sämre än 50 meter på grund av dimma?","option_a":"Du ska använda dimstrålkastare framtill och dimljus baktill","option_b":"Du ska stanna tills dimman lättar","option_c":"Du ska köra med helljus","option_d":"Du ska köra med varningsblinkers","correct":"A","explanation":"Vid sikt under 50 meter ska du använda främre dimstrålkastare och bakre dimljus. Anpassa hastigheten kraftigt efter sikten."},
  {"category":"Mörker & Sikt","difficulty":"easy","question":"Vilka ljus ska du alltid ha på i Sverige (dag och natt)?","option_a":"Helljus dagtid, halvljus nattetid","option_b":"Halvljus eller varselljus dygnet runt","option_c":"Bara halvljus nattetid","option_d":"Det finns inget krav på dagsljus","correct":"B","explanation":"I Sverige ska du köra med halvljus eller varselljus (DRL) dygnet runt, oavsett ljusförhållanden."},
  {"category":"Mörker & Sikt","difficulty":"normal","question":"När är det lämpligt att använda helljus?","option_a":"Alltid på motorväg","option_b":"På mörk väg utan mötande trafik och utan gatubelysning","option_c":"Alltid utanför tättbebyggt område","option_d":"Aldrig, halvljus räcker alltid","correct":"B","explanation":"Helljus används lämpligen på mörka vägar utan mötande trafik och utan tillräcklig gatubelysning. Byt alltid till halvljus när du möter eller kör bakom ett annat fordon."},

  # VÄGLAG & BROMSSTRÄCKA
  {"category":"Väglag & Bromssträcka","difficulty":"easy","question":"Hur förändras bromssträckan på is jämfört med torr asfalt?","option_a":"Den är ungefär densamma","option_b":"Den är 2 gånger längre","option_c":"Den kan vara upp till 10 gånger längre","option_d":"Den är 5 gånger längre","correct":"C","explanation":"På is kan bromssträckan vara upp till 10 gånger längre än på torr asfalt. Sänk hastigheten drastiskt vid halt väglag."},
  {"category":"Väglag & Bromssträcka","difficulty":"normal","question":"Vad bör du göra om du börjar glida på is?","option_a":"Bromsa hårt","option_b":"Accelerera för att få grepp","option_c":"Backa","option_d":"Ta bort gasen och styra försiktigt i önskad riktning","correct":"D","explanation":"Om bilen börjar glida ska du ta bort gasen och styra försiktigt i den riktning du vill köra. Undvik hårda rörelser med ratten."},
  {"category":"Väglag & Bromssträcka","difficulty":"normal","question":"Vad är 'aquaplaning' och hur undviker du det?","option_a":"Överhettning av bromsar — undvik kraftig bromsning","option_b":"Att däcken lyfter av vägbanan på en vattenfilm — sänk hastigheten och välj rätt däck","option_c":"Att bilen drar åt sidan — kontrollera däcktrycket","option_d":"Att bilen vibrerar vid hög hastighet","correct":"B","explanation":"Aquaplaning uppstår när däcken rider upp på en vattenfilm och förlorar kontakten med vägbanan. Sänk hastigheten och se till att däcken har bra mönster och rätt tryck."},
  {"category":"Väglag & Bromssträcka","difficulty":"hard","question":"Du kör 90 km/h. Ungefär hur lång är stoppsträckan på torr asfalt?","option_a":"45 meter","option_b":"60 meter","option_c":"75 meter","option_d":"90 meter","correct":"C","explanation":"I 90 km/h är reaktionssträckan ca 25 m (1 sek) och bromssträckan ca 50 m på torr asfalt, totalt ca 75 m."},
  {"category":"Väglag & Bromssträcka","difficulty":"normal","question":"Vilket bromssystem hjälper dig att styra bilen under kraftig bromsning?","option_a":"ABS (Antiblockersystem)","option_b":"ESP (Elektronisk stabilitetskontroll)","option_c":"Regenerativ bromsning","option_d":"Trumbroms","correct":"A","explanation":"ABS (Antilock Braking System) förhindrar att hjulen låser sig vid kraftig bromsning, vilket gör att du kan styra bilen även under nödbromsar."},
  {"category":"Väglag & Bromssträcka","difficulty":"easy","question":"Vad ska du tänka på när du kör efter ett tungt fordon på vått väglag?","option_a":"Hålla tätt bakom för att undvika stänk","option_b":"Öka säkerhetsavståndet — tung bil tar längre att stanna","option_c":"Köra om så snart möjligt","option_d":"Hålla samma avstånd som normalt","correct":"B","explanation":"Tunga fordon har längre bromssträcka och kastar upp mycket vatten. Håll ett extra stort säkerhetsavstånd."},
  {"category":"Väglag & Bromssträcka","difficulty":"hard","question":"Hur lång bör säkerhetsavståndet vara i sekunder bakom framförvarande bil?","option_a":"1 sekund","option_b":"2 sekunder (3 vid halt väglag)","option_c":"5 sekunder alltid","option_d":"Det beror bara på hastigheten i meter","correct":"B","explanation":"Tumregeln är 2 sekunders avstånd vid normala förhållanden. Vid halt väglag, mörker eller tät trafik ska du öka till minst 3–4 sekunder."},
]

def insert_batch(questions):
    data = json.dumps(questions).encode('utf-8')
    req = urllib.request.Request(
        f"{SUPABASE_URL}/rest/v1/driving_questions",
        data=data,
        headers={
            "apikey": ANON_KEY,
            "Authorization": f"Bearer {ANON_KEY}",
            "Content-Type": "application/json",
            "Prefer": "return=minimal"
        },
        method="POST"
    )
    try:
        with urllib.request.urlopen(req) as resp:
            return resp.status, "OK"
    except urllib.error.HTTPError as e:
        return e.code, e.read().decode('utf-8')

# Insert in batches of 20
batch_size = 20
total = len(QUESTIONS)
inserted = 0
for i in range(0, total, batch_size):
    batch = QUESTIONS[i:i+batch_size]
    status, msg = insert_batch(batch)
    if status in (200, 201):
        inserted += len(batch)
        print(f"Batch {i//batch_size+1}: {len(batch)} frågor inlagda OK")
    else:
        print(f"Batch {i//batch_size+1} FEL {status}: {msg[:200]}")

print(f"\nKlart! {inserted}/{total} frågor inlagda.")
