/**
 * New questions batch 3 — sparse categories
 * IDs 585–618
 * Run: node scripts/new_questions_batch3.js
 * Apply: node scripts/new_questions_batch3.js --apply
 */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

function wikimediaUrl(filename, size = 200) {
  const md5 = crypto.createHash('md5').update(filename).digest('hex');
  const p = md5[0] + '/' + md5[0] + md5[1] + '/' + filename;
  return `https://upload.wikimedia.org/wikipedia/commons/thumb/${p}/${size}px-${filename}.png`;
}

const newQuestions = [

  // ─── Körning med Släp ─────────────────────────────────────────────────────
  {
    id: 585,
    category: 'Körning med Släp',
    subcategory: 'Hastighet med släp',
    question_type: 'multiple_choice',
    question: 'Vad är maxhastigheten för personbil med lätt obromsat släp (totalvikt ≤ 750 kg) på landsväg?',
    option_a: '90 km/h',
    option_b: '80 km/h',
    option_c: '70 km/h',
    option_d: '50 km/h',
    options: { A: '90 km/h', B: '80 km/h', C: '70 km/h', D: '50 km/h' },
    correct: 'B',
    correctAnswer: 'B',
    explanation: 'Rätt svar är B. Med lätt obromsat släp (≤ 750 kg totalvikt) gäller max 80 km/h på landsväg. Med bromsad husvagn på motorväg gäller 80 km/h. Kontrollera alltid att hastighetsgränserna för fordonskombinationen följs. Lagrum: TF 4 kap.',
    law_reference: 'TF 4 kap',
    difficulty: 'medium',
    commonly_failed: true,
    image_url: wikimediaUrl('Sweden_road_sign_E8-80.svg'),
    image_description: 'Hastighetsgräns 80 km/h — maxhastighet med lätt släp',
    image_alt: 'Hastighetsgräns 80',
    image_type: 'vägmärke',
    requiresImage: false,
    imageStatus: 'auto-added-2026-06-05',
  },
  {
    id: 586,
    category: 'Körning med Släp',
    subcategory: 'Kopplingstyngd',
    question_type: 'multiple_choice',
    question: 'Vad menas med "kopplingstyngd" (kuggning) vid koppling av släpvagn?',
    option_a: 'Vikten av dragkroken',
    option_b: 'Den vertikala belastningen på dragkroken från kopplade släpet',
    option_c: 'Totalvikten av släpet',
    option_d: 'Vikten som sticker ut bakom bilen',
    options: { A: 'Vikten av dragkroken', B: 'Den vertikala belastningen på dragkroken från kopplade släpet', C: 'Totalvikten av släpet', D: 'Vikten som sticker ut bakom bilen' },
    correct: 'B',
    correctAnswer: 'B',
    explanation: 'Rätt svar är B. Kopplingstyngden (eller kopplingslast) är den vertikala kraft som ett kopplat släp utövar nedåt på dragkroken. Rätt kopplingstyngd (normalt 50-75 kg) förbättrar stabilitet. För låg kopplingstyngd → svajning. För hög → sämre styrning.',
    law_reference: 'TF 4 kap',
    difficulty: 'hard',
    commonly_failed: true,
    image_url: null,
    requiresImage: false,
  },
  {
    id: 587,
    category: 'Körning med Släp',
    subcategory: 'Stabilitet',
    question_type: 'multiple_choice',
    question: 'Varför bör du inte lasta tungt längst bak i en husvagn/trailer?',
    option_a: 'Det sliter mer på däcken',
    option_b: 'Det minskar kopplingstyngden och ökar risken för svajning',
    option_c: 'Det ökar kopplingstyngden för mycket',
    option_d: 'Det påverkar inte körningen',
    options: { A: 'Det sliter mer på däcken', B: 'Det minskar kopplingstyngden och ökar risken för svajning', C: 'Det ökar kopplingstyngden för mycket', D: 'Det påverkar inte körningen' },
    correct: 'B',
    correctAnswer: 'B',
    explanation: 'Rätt svar är B. Tung last längst bak i en trailer/husvagn minskar kopplingstyngden (den nedåttryckande kraften på dragkroken). För låg kopplingstyngd gör kombinationen instabil — husvagnen kan börja svänga (svajning). Lasten ska placeras framtill och lågt.',
    law_reference: 'TF 4 kap',
    difficulty: 'medium',
    commonly_failed: true,
    image_url: null,
    requiresImage: false,
  },
  {
    id: 588,
    category: 'Körning med Släp',
    subcategory: 'Bromsning',
    question_type: 'multiple_choice',
    question: 'Hur påverkar en bromsad husvagn bromssträckan jämfört med en obromsad?',
    option_a: 'Bromssträckan ökar lika mycket',
    option_b: 'Bromssträckan minskar — den bromsade husvagnen hjälper till att bromsa',
    option_c: 'Bromssträckan minskar men kontrollen försämras',
    option_d: 'Det spelar ingen roll',
    options: { A: 'Bromssträckan ökar lika mycket', B: 'Bromssträckan minskar — den bromsade husvagnen hjälper till att bromsa', C: 'Bromssträckan minskar men kontrollen försämras', D: 'Det spelar ingen roll' },
    correct: 'B',
    correctAnswer: 'B',
    explanation: 'Rätt svar är B. En bromsad husvagn/trailer har egna bromsar som aktiveras när dragbilen bromsar. Det förkortar bromssträckan jämfört med en obromsad trailer. En obromsad trailer skjuter på bakifrån vid inbromsning och förlänger bromssträckan.',
    law_reference: 'TF 4 kap',
    difficulty: 'medium',
    commonly_failed: false,
    image_url: null,
    requiresImage: false,
  },
  {
    id: 589,
    category: 'Körning med Släp',
    subcategory: 'Belysning',
    question_type: 'multiple_choice',
    question: 'Husvagnen är bredare än bilen. Vad krävs extra vid körning i mörker?',
    option_a: 'Inget extra behövs',
    option_b: 'Sidomarkeringsljus eller bredmarkering om husvagnen överstiger 2,10 m',
    option_c: 'Helljus på dragbilen',
    option_d: 'En medhjälpare med ficklampa',
    options: { A: 'Inget extra behövs', B: 'Sidomarkeringsljus eller bredmarkering om husvagnen överstiger 2,10 m', C: 'Helljus på dragbilen', D: 'En medhjälpare med ficklampa' },
    correct: 'B',
    correctAnswer: 'B',
    explanation: 'Rätt svar är B. Om husvagnen/trailern är bredare än 2,10 meter krävs sidomarkeringsljus (orange/vita framtill, röda baktill). Dessa indikerar fordonets fulla bredd för mötande trafik. Dragbilens bakljus täcker inte husvagnens bredd.',
    law_reference: 'TSVFS',
    difficulty: 'hard',
    commonly_failed: true,
    image_url: null,
    requiresImage: false,
  },
  {
    id: 590,
    category: 'Körning med Släp',
    subcategory: 'Lagar',
    question_type: 'multiple_choice',
    question: 'Vad måste du kontrollera INNAN du kopplar på en trailer?',
    option_a: 'Enbart kopplingsskålen',
    option_b: 'Kopplingsenhet, säkerhetsvajer/säkerhetskedja, elsladd, broms och belysning',
    option_c: 'Bara elsladden',
    option_d: 'Bara att hjulen sitter fast',
    options: { A: 'Enbart kopplingsskålen', B: 'Kopplingsenhet, säkerhetsvajer/säkerhetskedja, elsladd, broms och belysning', C: 'Bara elsladden', D: 'Bara att hjulen sitter fast' },
    correct: 'B',
    correctAnswer: 'B',
    explanation: 'Rätt svar är B. Innan körning med trailer ska du kontrollera: kopplingsenhet (korrekt låst), säkerhetsvajer/kedja (håller trailern om kopplingen lossar), elsladd (belysning och bromsar fungerar), broms, belysning och däcktryck på trailern.',
    law_reference: 'TF 4 kap',
    difficulty: 'medium',
    commonly_failed: false,
    image_url: null,
    requiresImage: false,
  },
  {
    id: 591,
    category: 'Körning med Släp',
    subcategory: 'Vändradie',
    question_type: 'multiple_choice',
    question: 'Varför tar en bil med husvagn eller lång trailer mer plats vid svängar?',
    option_a: 'Bilen bromsar sämre',
    option_b: 'Trailern följer en kortare kurva ("skär inåt") och kräver mer utrymme i innersväng',
    option_c: 'Bilen styr sämre',
    option_d: 'Det spelar ingen roll — en trailer följer exakt bilens spår',
    options: { A: 'Bilen bromsar sämre', B: 'Trailern följer en kortare kurva ("skär inåt") och kräver mer utrymme i innersväng', C: 'Bilen styr sämre', D: 'Det spelar ingen roll — en trailer följer exakt bilens spår' },
    correct: 'B',
    correctAnswer: 'B',
    explanation: 'Rätt svar är B. En trailer/husvagn skär inåt vid svängar — den tar en kortare inre kurva än bilen. Ju längre trailern är, desto mer skär den in. Sväng därför brett och kontrollera speglar noga för att undvika att trailerns inre hörn kolliderar med vägkanten eller cyklister.',
    law_reference: 'TF 3 kap',
    difficulty: 'medium',
    commonly_failed: true,
    image_url: null,
    requiresImage: false,
  },

  // ─── Bogsering & Lastsäkring ──────────────────────────────────────────────
  {
    id: 592,
    category: 'Bogsering & Lastsäkring',
    subcategory: 'Stångbogsering',
    question_type: 'multiple_choice',
    question: 'Vad är maxhastigheten vid stångbogsering (bogseringsstång, inte tross)?',
    option_a: '30 km/h',
    option_b: '50 km/h',
    option_c: '70 km/h',
    option_d: '80 km/h',
    options: { A: '30 km/h', B: '50 km/h', C: '70 km/h', D: '80 km/h' },
    correct: 'B',
    correctAnswer: 'B',
    explanation: 'Rätt svar är B. Vid stångbogsering (fast stång) är maxhastigheten 50 km/h. Vid linebogsering (rep/tross) är det 30 km/h. En stång ger bättre kontroll än ett rep och tillåter därför något högre hastighet.',
    law_reference: 'TF 4 kap',
    difficulty: 'medium',
    commonly_failed: true,
    image_url: null,
    requiresImage: false,
  },
  {
    id: 593,
    category: 'Bogsering & Lastsäkring',
    subcategory: 'Framskjuten last',
    question_type: 'multiple_choice',
    question: 'En last sticker ut mer än 1 meter FRAMFÖR fordonets front. Vad krävs?',
    option_a: 'Inget krävs om det är under 2 meter',
    option_b: 'En vit markering eller flagga framtill',
    option_c: 'En röd flagga framtill och varseltriangel baktill',
    option_d: 'Inget krävs om chauffören är medveten',
    options: { A: 'Inget krävs om det är under 2 meter', B: 'En vit markering eller flagga framtill', C: 'En röd flagga framtill och varseltriangel baktill', D: 'Inget krävs om chauffören är medveten' },
    correct: 'B',
    correctAnswer: 'B',
    explanation: 'Rätt svar är B. En last som sticker ut mer än 1 meter framtill ska markeras med en VIT reflexmarkering eller vit flagga. Last som sticker ut mer än 1 meter baktill ska markeras med RÖD reflexmarkering eller röd flagga. Syftet är att varna andra trafikanter.',
    law_reference: 'TF 4 kap',
    difficulty: 'hard',
    commonly_failed: true,
    image_url: null,
    requiresImage: false,
  },
  {
    id: 594,
    category: 'Bogsering & Lastsäkring',
    subcategory: 'Tyngdpunkt',
    question_type: 'multiple_choice',
    question: 'Hur påverkar en hög tyngdpunkt (last lastas högt upp) bilens stabilitet?',
    option_a: 'Förbättrar stabiliteten',
    option_b: 'Försämrar stabiliteten och ökar risken för välta i kurvor',
    option_c: 'Påverkar inte stabiliteten',
    option_d: 'Förbättrar stabiliteten men minskar bromsförmågan',
    options: { A: 'Förbättrar stabiliteten', B: 'Försämrar stabiliteten och ökar risken för välta i kurvor', C: 'Påverkar inte stabiliteten', D: 'Förbättrar stabiliteten men minskar bromsförmågan' },
    correct: 'B',
    correctAnswer: 'B',
    explanation: 'Rätt svar är B. Hög tyngdpunkt höjer gravitationscentrum vilket gör fordonet mer benäget att välta i kurvor. Lasta alltid tungt gods lågt och nära mitten av lastbäraren. Högt placerad last skapar kraftiga rörelser vid kurvtagning och inbromsning.',
    law_reference: 'TF 4 kap',
    difficulty: 'medium',
    commonly_failed: false,
    image_url: null,
    requiresImage: false,
  },
  {
    id: 595,
    category: 'Bogsering & Lastsäkring',
    subcategory: 'Kontrollskyldighet',
    question_type: 'multiple_choice',
    question: 'En poliskontroll avslöjar att lasten är dåligt säkrad. Vem är ansvarig?',
    option_a: 'Lastaren (den som lastade bilen)',
    option_b: 'Föraren är alltid ytterst ansvarig för att lasten är säkrad',
    option_c: 'Fordonsägaren, inte föraren',
    option_d: 'Ingen är ansvarig om lasten inte har ramlat av',
    options: { A: 'Lastaren (den som lastade bilen)', B: 'Föraren är alltid ytterst ansvarig för att lasten är säkrad', C: 'Fordonsägaren, inte föraren', D: 'Ingen är ansvarig om lasten inte har ramlat av' },
    correct: 'B',
    correctAnswer: 'B',
    explanation: 'Rätt svar är B. Föraren har alltid det yttersta ansvaret för att lasten är korrekt säkrad. Även om en annan person lastade bilen ska föraren kontrollera och godkänna lastens säkring innan avfärd. Osäkrad last är straffbelagd och ytterst farlig.',
    law_reference: 'TF 4 kap 22§',
    difficulty: 'easy',
    commonly_failed: false,
    image_url: null,
    requiresImage: false,
  },

  // ─── Vägtunnlar ───────────────────────────────────────────────────────────
  {
    id: 596,
    category: 'Vägtunnlar',
    subcategory: 'Mötande brand',
    question_type: 'multiple_choice',
    question: 'Du kör in i en tunnel och ser ett brinnande fordon framför dig. Vad gör du?',
    option_a: 'Stanna bakom det brinnande fordonet och vänta på hjälp',
    option_b: 'Om möjligt: backa ut ur tunneln. Om inte: parkera vid sidan, ta nycklarna, gå mot den NÄRMASTE nödutgången',
    option_c: 'Kör snabbt förbi det brinnande fordonet',
    option_d: 'Stanna, stäng av motor och vänta i bilen',
    options: {
      A: 'Stanna bakom det brinnande fordonet och vänta på hjälp',
      B: 'Om möjligt: backa ut ur tunneln. Om inte: parkera vid sidan, ta nycklarna, gå mot den NÄRMASTE nödutgången',
      C: 'Kör snabbt förbi det brinnande fordonet',
      D: 'Stanna, stäng av motor och vänta i bilen'
    },
    correct: 'B',
    correctAnswer: 'B',
    explanation: 'Rätt svar är B. Vid brand i en tunnel: backa ut om det är säkert. Annars parkera vid sidan (lämna OLåst), ta nyckeln, gå mot NÄRMASTE nödutgång (inte nödvändigtvis entrén). Stanna INTE i bilen — rök och eld är dödliga. Ring 112 när du är säker.',
    law_reference: 'Tunnelsäkerhetslagen',
    difficulty: 'hard',
    commonly_failed: true,
    image_url: null,
    requiresImage: false,
  },
  {
    id: 597,
    category: 'Vägtunnlar',
    subcategory: 'Regler',
    question_type: 'multiple_choice',
    question: 'Varför är det förbjudet att stanna i en vägtunnel (utom vid nödsituationer)?',
    option_a: 'Det är inte förbjudet — bara olämpligt',
    option_b: 'Avgaser samlas och risk för brand/kollision gör stillastående mycket farligt',
    option_c: 'Bara för att det saktas ner trafikflödet',
    option_d: 'Ljusförhållandena är dåliga',
    options: {
      A: 'Det är inte förbjudet — bara olämpligt',
      B: 'Avgaser samlas och risk för brand/kollision gör stillastående mycket farligt',
      C: 'Bara för att det saktas ner trafikflödet',
      D: 'Ljusförhållandena är dåliga'
    },
    correct: 'B',
    correctAnswer: 'B',
    explanation: 'Rätt svar är B. Tunnlar är slutna miljöer där avgaser (CO, CO2) snabbt kan nå farliga nivåer. Brand i tunnel är extremt farlig eftersom utrymmet är begränsat och räddningstjänsten har svårt att komma in. Stanna är förbjudet och parkering är alltid förbjudet. (TF 9 kap tunnelbestämmelserna)',
    law_reference: 'TF 9 kap',
    difficulty: 'easy',
    commonly_failed: false,
    image_url: null,
    requiresImage: false,
  },
  {
    id: 598,
    category: 'Vägtunnlar',
    subcategory: 'Säkerhetsavstånd',
    question_type: 'multiple_choice',
    question: 'Varför ska du hålla extra stort säkerhetsavstånd inne i en lång tunnel?',
    option_a: 'Belysningen är dåligare',
    option_b: 'Möjligheterna att undkomma vid brand/haveri är begränsade och det kan ta lång tid att utrymma',
    option_c: 'Hastigheten är högre i tunnel',
    option_d: 'Det finns inga speciella skäl',
    options: {
      A: 'Belysningen är dåligare',
      B: 'Möjligheterna att undkomma vid brand/haveri är begränsade och det kan ta lång tid att utrymma',
      C: 'Hastigheten är högre i tunnel',
      D: 'Det finns inga speciella skäl'
    },
    correct: 'B',
    correctAnswer: 'B',
    explanation: 'Rätt svar är B. I en tunnel finns begränsade utrymnings- och räddningsmöjligheter. Om du krockar in i bilen framför dig kan kedjeolyckor blockera hela tunneln och omöjliggöra utrymning. Minst 50 meters säkerhetsavstånd rekommenderas för att kunna reagera och undvika kollision.',
    law_reference: 'Tunnelsäkerhetslagen',
    difficulty: 'medium',
    commonly_failed: false,
    image_url: null,
    requiresImage: false,
  },
  {
    id: 599,
    category: 'Vägtunnlar',
    subcategory: 'Nödutrustning',
    question_type: 'multiple_choice',
    question: 'Vad hittar du normalt i en nödnisch (SOS-nisch) längs en tunnelvägg?',
    option_a: 'Bara nödtelefon',
    option_b: 'Nödtelefon och brandsläckare',
    option_c: 'Nödtelefon, brandsläckare och förbandslåda',
    option_d: 'Enbart brandsläckare',
    options: {
      A: 'Bara nödtelefon',
      B: 'Nödtelefon och brandsläckare',
      C: 'Nödtelefon, brandsläckare och förbandslåda',
      D: 'Enbart brandsläckare'
    },
    correct: 'B',
    correctAnswer: 'B',
    explanation: 'Rätt svar är B. I tunnlars nödnischer finns normalt: nödtelefon (kopplad till räddningsledning) och brandsläckare. I vissa tunnlar finns också defibrillator. Nödtelefonerna är orange och placeras med jämna mellanrum längs tunnelväggen.',
    law_reference: 'Tunnelsäkerhetslagen',
    difficulty: 'medium',
    commonly_failed: true,
    image_url: null,
    requiresImage: false,
  },

  // ─── Nödsituationer ───────────────────────────────────────────────────────
  {
    id: 600,
    category: 'Nödsituationer',
    subcategory: 'Älgolycka',
    question_type: 'multiple_choice',
    question: 'Du kör på en landsväg och en älg hoppar ut framför dig. Du kan inte undvika kollision. Vad ska du prioritera?',
    option_a: 'Svänga kraftigt för att missa älgen',
    option_b: 'Bromsa så hårt som möjligt rakt fram — sväng bara om det finns plats utan att hamna i diket',
    option_c: 'Accelerera för att ta kraften kortare',
    option_d: 'Stäng av motorn direkt',
    options: {
      A: 'Svänga kraftigt för att missa älgen',
      B: 'Bromsa så hårt som möjligt rakt fram — sväng bara om det finns plats utan att hamna i diket',
      C: 'Accelerera för att ta kraften kortare',
      D: 'Stäng av motorn direkt'
    },
    correct: 'B',
    correctAnswer: 'B',
    explanation: 'Rätt svar är B. Vid oundviklig kollision med älg: bromsa maximalt rakt fram. Att svänga kraftigt riskerar att du kör av vägen eller in i mötande trafik — ofta farligare än älgkollisionen. Krama in huvudet, luta dig bakåt och låt airbagen/bältet skydda dig. Älg på tak är vanlig och extremt farlig.',
    law_reference: 'TF 2 kap',
    difficulty: 'hard',
    commonly_failed: true,
    image_url: null,
    requiresImage: false,
  },
  {
    id: 601,
    category: 'Nödsituationer',
    subcategory: 'El-olycka',
    question_type: 'multiple_choice',
    question: 'Du är vid en trafikolycka och elledningar hänger ned på ett fordon. Vad gör du?',
    option_a: 'Dra ut de skadade ur fordonet omedelbart',
    option_b: 'Stanna på avstånd, ring 112 och kontakta elnätsägaren — RÖR INTE fordonet',
    option_c: 'Klipp av kabeln med en sax',
    option_d: 'Stå på marken och rör vid kabeln snabbt för att känna om det är ström',
    options: {
      A: 'Dra ut de skadade ur fordonet omedelbart',
      B: 'Stanna på avstånd, ring 112 och kontakta elnätsägaren — RÖR INTE fordonet',
      C: 'Klipp av kabeln med en sax',
      D: 'Stå på marken och rör vid kabeln snabbt för att känna om det är ström'
    },
    correct: 'B',
    correctAnswer: 'B',
    explanation: 'Rätt svar är B. Elledningar på ett fordon är extremt farliga — RÖRV INTE fordonet eller kabeln. Markkontakt kan sprida ström (stegelspänning). Ring 112 och elnätsleverantören omedelbart. Vänta tills elnätsbolaget bekräftat att strömmen är bruten. Att dra ut skadade kan döda dig och dem.',
    law_reference: 'Räddningstjänstlagen',
    difficulty: 'hard',
    commonly_failed: true,
    image_url: null,
    requiresImage: false,
  },
  {
    id: 602,
    category: 'Nödsituationer',
    subcategory: 'Livräddning',
    question_type: 'multiple_choice',
    question: 'En skadad person vid olyckan verkar ha nackskada. Hur hanterar du detta?',
    option_a: 'Flytta personen till ett säkrare ställe omedelbart oavsett skada',
    option_b: 'Rör personen minimalt — flytta bara om livshotande fara (brand, trafik). Håll nacken stilla och vänta på ambulans',
    option_c: 'Böj nacken bakåt för att öppna luftvägen',
    option_d: 'Sätt personen i sittande ställning',
    options: {
      A: 'Flytta personen till ett säkrare ställe omedelbart oavsett skada',
      B: 'Rör personen minimalt — flytta bara om livshotande fara (brand, trafik). Håll nacken stilla och vänta på ambulans',
      C: 'Böj nacken bakåt för att öppna luftvägen',
      D: 'Sätt personen i sittande ställning'
    },
    correct: 'B',
    correctAnswer: 'B',
    explanation: 'Rätt svar är B. Vid misstänkt nackskada: rör personen minimalt. Felaktigt förflyttning kan förvärra ryggmärgsskada och orsaka permanent förlamning. Flytta bara om personen befinner sig i omedelbar livsfara (brand, trafik). Håll huvudet/nacken stabiliserat och ring 112.',
    law_reference: 'Räddningstjänstlagen',
    difficulty: 'medium',
    commonly_failed: true,
    image_url: null,
    requiresImage: false,
  },
  {
    id: 603,
    category: 'Nödsituationer',
    subcategory: 'Barn i varm bil',
    question_type: 'multiple_choice',
    question: 'Du ser ett barn inlåst i en bil på en varm sommardag. Barnet verkar opåverkat men du kan inte nå föräldrarna. Vad gör du?',
    option_a: 'Vänta 30 minuter och ring sedan 112',
    option_b: 'Ring 112 direkt. Om barnets tillstånd försämras snabbt kan du krossa rutan — du kan ha nödrätt',
    option_c: 'Ring bara polisen, inte SOS 112',
    option_d: 'Gå och leta efter föräldrarna i 15 minuter',
    options: {
      A: 'Vänta 30 minuter och ring sedan 112',
      B: 'Ring 112 direkt. Om barnets tillstånd försämras snabbt kan du krossa rutan — du kan ha nödrätt',
      C: 'Ring bara polisen, inte SOS 112',
      D: 'Gå och leta efter föräldrarna i 15 minuter'
    },
    correct: 'B',
    correctAnswer: 'B',
    explanation: 'Rätt svar är B. Ring 112 OMEDELBART. Bilar kan nå livsfarliga temperaturer på 10-15 minuter på en varm dag. Om barnet tappar medvetandet eller slutar röra sig och du inte kan nå 112 snabbt nog, kan du ha nödrätt att krossa rutan. Nödrätt ger ansvarsfrihet för skadegörelse vid livsfara.',
    law_reference: 'BrB 24 kap (nödrätt)',
    difficulty: 'medium',
    commonly_failed: false,
    image_url: null,
    requiresImage: false,
  },
  {
    id: 604,
    category: 'Nödsituationer',
    subcategory: 'Stopp på motorväg',
    question_type: 'multiple_choice',
    question: 'Bilen stannar mitt på motorvägen (maskinfel). Vad är det VIKTIGASTE du gör DIREKT?',
    option_a: 'Stäng av motorn och börja ringa försäkringsbolaget',
    option_b: 'Slå på varningsblinkers OMEDELBART, försök rulla till vägrenen, sätt ut varningstriangel och utrym fordonet till bakom räcket',
    option_c: 'Öppna huven och vifta till mötande bilar',
    option_d: 'Stanna kvar i bilen och vänta på bärgning',
    options: {
      A: 'Stäng av motorn och börja ringa försäkringsbolaget',
      B: 'Slå på varningsblinkers OMEDELBART, försök rulla till vägrenen, sätt ut varningstriangel och utrym fordonet till bakom räcket',
      C: 'Öppna huven och vifta till mötande bilar',
      D: 'Stanna kvar i bilen och vänta på bärgning'
    },
    correct: 'B',
    correctAnswer: 'B',
    explanation: 'Rätt svar är B. Prioritetsordning vid stopp på motorväg: 1) Varningsblinkers DIREKT, 2) rulla av till vägren om möjligt, 3) utrym alla passagerare BAKOM räcket/vägvallar (INTE stå på körbanan), 4) sätt ut varningstriangel (minst 100m bak), 5) ring bärgning/112. Att stanna i bilen är livsfarligt.',
    law_reference: 'TF 9 kap',
    difficulty: 'medium',
    commonly_failed: true,
    image_url: null,
    requiresImage: false,
  },
  {
    id: 605,
    category: 'Nödsituationer',
    subcategory: 'Kraftig blödning',
    question_type: 'multiple_choice',
    question: 'En skadad person vid en trafikolycka har kraftig blödning. Vad ska du göra omedelbart?',
    option_a: 'Lägga personen i stabilt sidoläge och vänta',
    option_b: 'Pressa hårt mot såret med ett tryckt förbandet eller händerna och håll trycket tills ambulansen kommer',
    option_c: 'Lägga på ett löst förband utan tryck',
    option_d: 'Lyfta den skadade armen/benet och vänta',
    options: {
      A: 'Lägga personen i stabilt sidoläge och vänta',
      B: 'Pressa hårt mot såret med ett tryckt förbandet eller händerna och håll trycket tills ambulansen kommer',
      C: 'Lägga på ett löst förband utan tryck',
      D: 'Lyfta den skadade armen/benet och vänta'
    },
    correct: 'B',
    correctAnswer: 'B',
    explanation: 'Rätt svar är B. Vid kraftig blödning: applicera DIREKT tryck mot såret med händerna eller ett förband och HÅLL trycket. Lyft inte händerna — det stoppar koaguleringen. Hårdt direkttryck är den effektivaste metoden att stoppa kraftig blödning. Ring 112 parallellt.',
    law_reference: 'Första hjälpen-riktlinjer',
    difficulty: 'easy',
    commonly_failed: false,
    image_url: null,
    requiresImage: false,
  },

  // ─── Trafikregler (motorvägsspecifika) ────────────────────────────────────
  {
    id: 606,
    category: 'Trafikregler',
    subcategory: 'Motorväg',
    question_type: 'multiple_choice',
    question: 'Vilka fordon är FÖRBJUDNA att köra på motorväg?',
    option_a: 'Mopeder, cyklister, traktorer och fordon som inte klarar 40 km/h',
    option_b: 'Motorcyklar och husbilar',
    option_c: 'Lastbilar med tillstånd',
    option_d: 'Bussar med fler än 30 passagerare',
    options: {
      A: 'Mopeder, cyklister, traktorer och fordon som inte klarar 40 km/h',
      B: 'Motorcyklar och husbilar',
      C: 'Lastbilar med tillstånd',
      D: 'Bussar med fler än 30 passagerare'
    },
    correct: 'A',
    correctAnswer: 'A',
    explanation: 'Rätt svar är A. På motorväg är mopeder, cyklister, traktorer, fordon som inte klarar minimihastighetskravet på 40 km/h samt gående förbjudna (TF 9 kap 1§). Motorcyklar, husbilar, lastbilar och bussar är tillåtna. Förbudet skyddar snabb trafik från långsamma fordon.',
    law_reference: 'TF 9 kap 1§',
    difficulty: 'easy',
    commonly_failed: false,
    image_url: wikimediaUrl('Sweden_road_sign_F5.svg'),
    image_description: 'Motorvägsskylten F5 — motorväg börjar',
    image_alt: 'Motorväg F5',
    image_type: 'vägmärke',
    requiresImage: false,
    imageStatus: 'auto-added-2026-06-05',
  },

  // ─── Korsningar (extra) ───────────────────────────────────────────────────
  {
    id: 607,
    category: 'Korsningar',
    subcategory: 'Rondell',
    question_type: 'multiple_choice',
    question: 'Du kör in i en rondell och ska svänga av vid tredje avfarten. Vilken signal använder du?',
    option_a: 'Blinka höger redan när du kör in',
    option_b: 'Kör in utan blinkers, blinka höger när du passerat ANDRA avfarten och ska ta den tredje',
    option_c: 'Blinka vänster när du kör in, höger när du svänger av',
    option_d: 'Blinkers behövs inte i rondell',
    options: {
      A: 'Blinka höger redan när du kör in',
      B: 'Kör in utan blinkers, blinka höger när du passerat ANDRA avfarten och ska ta den tredje',
      C: 'Blinka vänster när du kör in, höger när du svänger av',
      D: 'Blinkers behövs inte i rondell'
    },
    correct: 'B',
    correctAnswer: 'B',
    explanation: 'Rätt svar är B. I rondell: kör in utan blinkers (eller vänster om du tar mer än halva rondellen). Blinka HÖGER när du passerat avfarten INNAN den du ska ta. Kör aldrig in i rondell med höger blinker — det signalerar att du tar första avfarten.',
    law_reference: 'TF 3 kap',
    difficulty: 'hard',
    commonly_failed: true,
    image_url: wikimediaUrl('Sweden_road_sign_A8.svg'),
    image_description: 'Varning för rondell (A8) — cirkulär körning med pilsymbol',
    image_alt: 'Rondell A8',
    image_type: 'vägmärke',
    requiresImage: false,
    imageStatus: 'auto-added-2026-06-05',
  },
  {
    id: 608,
    category: 'Korsningar',
    subcategory: 'Spårvagn',
    question_type: 'multiple_choice',
    question: 'Du ska köra om en spårvagn som stannat för att ta upp passagerare. Vad gäller?',
    option_a: 'Du kan köra om spårvagnen om det är säkert',
    option_b: 'Du måste stanna och vänta tills passagerarna stigit ombord och spårvagnen kört',
    option_c: 'Du ska sakta ned men behöver inte stanna',
    option_d: 'Du kan köra om i vänstertrafik',
    options: {
      A: 'Du kan köra om spårvagnen om det är säkert',
      B: 'Du måste stanna och vänta tills passagerarna stigit ombord och spårvagnen kört',
      C: 'Du ska sakta ned men behöver inte stanna',
      D: 'Du kan köra om i vänstertrafik'
    },
    correct: 'B',
    correctAnswer: 'B',
    explanation: 'Rätt svar är B. Fordon ska stanna och vänta när en spårvagn stannar för att ta upp eller lämna av passagerare (TF 3 kap). Passagerarna rör sig ofta framför spårvagnen. Du får inte köra förbi förrän alla passagerare är säkert ombord och spårvägen rör sig igen.',
    law_reference: 'TF 3 kap 67§',
    difficulty: 'medium',
    commonly_failed: true,
    image_url: null,
    requiresImage: false,
  },
  {
    id: 609,
    category: 'Korsningar',
    subcategory: 'Gående',
    question_type: 'multiple_choice',
    question: 'Du svänger in på en gata och en gående vill korsa den gatan (utan övergångställe). Vad gäller?',
    option_a: 'Gående har alltid företräde',
    option_b: 'Du har företräde — gående ska vänta',
    option_c: 'Du ska lämna gående skälig möjlighet att passera om du svänger in från en annan väg',
    option_d: 'Gående har företräde bara om de kliver ut framför bilen',
    options: {
      A: 'Gående har alltid företräde',
      B: 'Du har företräde — gående ska vänta',
      C: 'Du ska lämna gående skälig möjlighet att passera om du svänger in från en annan väg',
      D: 'Gående har företräde bara om de kliver ut framför bilen'
    },
    correct: 'C',
    correctAnswer: 'C',
    explanation: 'Rätt svar är C. Utanför övergångställe har gående normalt inte företräde. Men TF 3 kap 61§ säger att den som svänger in ska lämna gående skälig möjlighet att passera. I praktiken: var beredd att stanna och låt gående passera tryggt. Vid övergångställe har gående alltid företräde.',
    law_reference: 'TF 3 kap 61§',
    difficulty: 'hard',
    commonly_failed: true,
    image_url: null,
    requiresImage: false,
  },

  // ─── Väglag & Bromssträcka (extra) ───────────────────────────────────────
  {
    id: 610,
    category: 'Väglag & Bromssträcka',
    subcategory: 'Däcktryck',
    question_type: 'multiple_choice',
    question: 'Hur påverkar lågt däcktryck körning och säkerhet?',
    option_a: 'Bättre grepp och kortare bromssträcka',
    option_b: 'Sämre grepp, längre bromssträcka, ökad risk för punktering och ökat bränsleförbrukning',
    option_c: 'Ingen påverkan om trycket inte är under hälften',
    option_d: 'Bara bränsleförbrukningen ökar',
    options: {
      A: 'Bättre grepp och kortare bromssträcka',
      B: 'Sämre grepp, längre bromssträcka, ökad risk för punktering och ökat bränsleförbrukning',
      C: 'Ingen påverkan om trycket inte är under hälften',
      D: 'Bara bränsleförbrukningen ökar'
    },
    correct: 'B',
    correctAnswer: 'B',
    explanation: 'Rätt svar är B. Lågt däcktryck ger: sämre väggrepp (mer däck böjer sig), längre bromssträcka, ökad risk för punktering (däcket överhettas), ökat bränsleförbrukning (rullmotstånd ökar) och försämrad styrning. Kontrollera däcktryck regelbundet — minst en gång i månaden.',
    law_reference: 'TF 4 kap',
    difficulty: 'easy',
    commonly_failed: false,
    image_url: null,
    requiresImage: false,
  },

];

console.log('New questions to add:', newQuestions.length);
newQuestions.forEach(q => console.log('  Q'+q.id+' ['+q.category+']: '+q.question.slice(0,65)));

if (process.argv.includes('--apply')) {
  const dataPath = path.join(__dirname, '../final_questions.json');
  const data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

  // Verify no ID conflicts
  const existingIds = new Set(data.questions.map(q => q.id));
  const conflicts = newQuestions.filter(q => existingIds.has(q.id));
  if (conflicts.length > 0) {
    console.error('ID CONFLICTS:', conflicts.map(q => q.id));
    process.exit(1);
  }

  data.questions.push(...newQuestions);
  data.metadata = data.metadata || {};
  data.metadata.total = data.questions.length;
  data.metadata.lastUpdated = new Date().toISOString().split('T')[0];

  fs.writeFileSync(dataPath, JSON.stringify(data, null, 2), 'utf8');
  console.log('\n✅ Added', newQuestions.length, 'questions. Total:', data.questions.length);
} else {
  console.log('\n--- DRY RUN — add --apply to save ---');
}
